### PR TITLE
Alternative to fix JPEG parsing (and improve speed) - use go-libjpeg

### LINKED ISSUE #1102: JPEG coverArt which displays fine unresized, fails on server-side resize
### Description
I saw a bunch of "No cover" blue records where I expected to see album art, both in
iSub and the native Navidrome web interface.
Inspecting the logs showed messages such as:
```
WARN[0086] Error extracting image                        error="invalid JPEG format: short Huffman data" path="/tank/whorfin/Audio/Musiq/Erik Wøllo/Infinite Moments (Album)/04 Infinite Moments Pt. 4.flac" requestId=server/B6xcOgmykV-000049 size=300
```
I tried swapping the `CoverArtPriority` to give precedence to local jpg, and also discovered this doesn't seem to resolve at runtime but required a _full_ rescan.  Then I saw:
```
WARN[0025] Error extracting image                        error="invalid JPEG format: short Huffman data" path="/tank/whorfin/Audio/Musiq/Erik Wøllo/Infinite Moments (Album)/cover.jpg" requestId=server/h04pDUthes-000027 size=300
```
As an aside, even without caching, any attempts to trigger this again resulted in no messages until I nuked and regenerated the database.  I was surprised by that.

The issue seems _maybe_ related to https://github.com/golang/go/issues/10447

I've attached an example; as you can see, it displays fine on the web.  And, I would imagine, if covers were not resized server-side, they'd display in the Navidrome web-UI.  But the artwork.go code which resizes covers is failing to decode them, because the golang library is too persnickety.  `sxiv` displays the image fine.  "verbose" mode to `gm` does reveal a premature JPEG end, but plain ol' `identify` does _not_ declare the image corrupted or truncated.
```
$ gm identify 00cover-bug.jpg
00cover-bug.jpg JPEG 1400x1400+0+0 DirectClass 8-bit 353.9Ki 0.000u 0m:0.000010s
gm identify: Premature end of JPEG file (00cover-bug.jpg).
$ identify 00cover-bug.jpg
00cover-bug.jpg JPEG 1400x1400 1400x1400+0+0 8-bit sRGB 362408B 0.000u 0:00.000
$ file 00cover-bug.jpg
00cover-bug.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, progressive, precision 8, 1400x1400, components 3
```

### Expected Behaviour

I'd like covers to display when resized just as they would display un-resized.
If a basic image viewer or web display can display the image, it would be excellent if Navidrome could decode it as well.
Put another way, I'd expect server-side resizing to behave just like client-side (browser) resizing, if not better.

### Steps to reproduce
Try adding the attached cover such that it will be picked up as coverart.
Observe it displays as a "missing cover" blue Serrato record, and an error is thrown in the logs.

### Platform information

 - Navidrome version: 0.42.1-SNAPSHOT (3e8d3e78)  (same results with 0.41.1)
 - Browser and version:  chrome, firefox, iSub - not the issue
 - Operating System: built from source on illumos

### Additional information

Any other information that may be relevant or give context to the problem.

00cover-bug

### PR DESCRIPTION
**Pull request by whorfin**
Fixes #1102, alternative to https://github.com/navidrome/navidrome/pull/1123

I know you are reluctant to increase c-library dependencies
but..
libjpeg-turbo is literally everywhere on everything, and it is what Mozilla/firefox and chrome use, so I would argue it is "what users expect"
It is very fast, but best of all - incredibly tolerant
It also totally fixes my library

### CODE REVIEW

**Comment by whorfin** [comment]
OK, I think the problem here is no longer mine, ie the libjpeg dependency works now with the simple apt update
wire is failing and i don't even

**Comment by deluan** [comment]
Hey @whorfin , sorry for the long delay in replying to your PRs. IMHO, Both solutions are suboptimal:

**The patched jpeg** code inside Navidrome's own codebase is not great. It brings a lot of tech debt, and will not be maintained. If we want to go with that approach, I think it would be better for it to live in its own package/project, and add a dependency for it in ND. Even then, I'm not equipped to evaluate if the "fix" is correct and if it could cause any other issues

**This approach here** (using external libjpeg), has its own challenges, as you probably noticed. Using an external C library is a hassle as Navidrome is statically linked, and doesn't depend on any external libs being installed in the system. This is one of the strengths of ND: Plug and Play, zero dependencies. For that to work, we need to be able to build it statically in all supported platforms. The step that is failing in the pipeline is built in a [custom docker image](https://github.com/navidrome/ci-goreleaser/blob/master/Dockerfile), that was prepared for this purpose. It was a pain to get it right for taglib, for all platforms, and I can imagine it will be also painful for libjpeg, if we decide to go this route.

Furthermore, I won't have time to look into fixing the custom docker image anytime soon, as it is very time consuming. 

Anyway, I still think the solution is to create a fallback in the image extraction code, to use `ffmpeg` when the current image extraction/resize method fails.

**Comment by whorfin** [comment]
OK

I agree on the patched go code, and am just poking upstream about improving the library.  But...

As a last plea for the libjpeg-turbo route - it is indeed a C dependency (like taglib), but it is a library that exists on every platform.  I really do think the fact that it is the "jpeg decoding method for the internet" makes it the most user-friendly - if your web browser shows an image, this method will show it too.  Method of least surprise.  And it is incredibly fast.

Of course it's your decision, and I get the pain of managing the custom docker image, although this might help:
https://github.com/libjpeg-turbo/docker

Cheers!

**Comment by jvoisin** [comment]
I do agree with @deluan , I prefer to use a memory-safe-ish language to parse images.

**Pull request closed without merging**
