### PR TITLE
scanner/ffmpeg: change to use ffprobe

### PR DESCRIPTION
**Pull request by vs49688**
ffprobe can output JSON and should be shipped anywhere ffmpeg is.

Handling JSON is much nicer than unstructured text.

Note that I removed some tests that no longer make sense after the change, e.g. the TBPM, FBPM, and multi-line comment tests.

### CODE REVIEW

**Comment by deluan** [comment]
Thanks for this, I do agree that `ffprobe` is a better metadata extractor, and actually I originally implemented it with `ffprobe` (that's why the config option is called _ProbeCommand_) but unfortunately you missed one important feature of `ffmpeg` vs `ffprobe`: Batching! Please read this: https://github.com/navidrome/navidrome/pull/1294#issuecomment-903340088

**Comment by vs49688** [comment]
Ah, I completely missed that thread. How about linking with libav{format,codec} and pulling out the data directly?

Could also get rid of the need for an external compressor that way too...

**Comment by deluan** [comment]
> Ah, I completely missed that thread. How about linking with libav{format,codec} and pulling out the data directly?

Linking to C libraries make the project very complex to maintain (see explanation here: https://github.com/navidrome/navidrome/pull/1124#issuecomment-849677752). SQLite3 and (specially) TagLib already give me enough headaches... Check the [docker image](https://github.com/navidrome/ci-goreleaser/blob/master/Dockerfile) I have to maintain to be able to build Navidrome statically

> Could also get rid of the need for an external compressor that way too...

This goes against the architecture decision of allowing external transcoders to be used to support formats unknown to Navidrome (see https://github.com/navidrome/navidrome/issues/351#issuecomment-913116433)

Can I ask you what is your motivation to get rid of `ffmpeg`? Is it causing any issues?

**Comment by vs49688** [comment]
> > Ah, I completely missed that thread. How about linking with libav{format,codec} and pulling out the data directly?
> 
> Linking to C libraries make the project very complex to maintain (see explanation here: [#1124 (comment)](https://github.com/navidrome/navidrome/pull/1124#issuecomment-849677752)). SQLite3 and (specially) TagLib already give me enough headaches... Check the [docker image](https://github.com/navidrome/ci-goreleaser/blob/master/Dockerfile) I have to maintain to be able to build Navidrome statically
> 
> > Could also get rid of the need for an external compressor that way too...
> 
> This goes against the architecture decision of allowing external transcoders to be used to support formats unknown to Navidrome (see [#351 (comment)](https://github.com/navidrome/navidrome/issues/351#issuecomment-913116433))
> 

Fair enough, I wasn't aware that was intended.

> Can I ask you what is your motivation to get rid of `ffmpeg`? Is it causing any issues?

No, not at all. I wanted to start off with something relatively simple to get familiar with the codebase, before I tackle https://github.com/navidrome/navidrome/issues/489.

**Comment by deluan** [comment]
> No, not at all. I wanted to start off with something relatively simple to get familiar with the codebase, before I tackle #489.

Ah, I see. Your code looks good to me but unfortunately, for the reasons above, I'll not be able to merge it, ok? Closing this now, but feel free to reach out (preferable in Discord) to discuss #489

**Pull request closed without merging**
