### PR TITLE
Add Gruvbox Dark color theme

### PR DESCRIPTION
**Pull request by vlfldr**
Adds a Gruvbox Dark color theme. Successfully built and tested

### CODE REVIEW

**Comment by deluan** [comment]
Thanks! Screenshots?

**Comment by rsammelson** [comment]
Here are some screenshots:
image
image
image
image
image

**Comment by deluan** [comment]
Nice! Can you please fix the formatting issue? After that it is good to merge, thanks!

**Comment by vlfldr** [comment]
Thank you @rsammelson for adding screenshots! Ran prettier and pushed another commit to correct formatting

**Pull request merged**
