### PR TITLE
Expose OpenSubsonic fields Genres, MusicBrainzId, Bpm, Comment

### PR DESCRIPTION
**Pull request by dweymouth**
Expose OpenSubsonic fields that Navidrome already supports internally.

Tested with a small test library on:
* Supersonic (supports OpenSubsonic) - mutli genres appear
* Sonixd
* Jamstash
* iSub

Adds to `AlbumID3`:
* `genres`
* `musicBrainzId`

Adds to `Child`:
* `genres`
* `bpm`
* `comment`

### CODE REVIEW

**Comment by deluan** [comment]
Hey @dweymouth, can you make some tests with other clients besides Supersonic? Maybe Some old ones like Jamstash and DSub? That would be very helpful. If they don't break, I think we are good to merge this. (by the way, these are approved, "production" OpenSubsonic attributes, right?)

**Comment by dweymouth** [comment]
I tested this on a few older Subsonic clients (see PR description) @deluan I do recommend you test this on DSub if possible before merging too

**Comment by Tolriq** [comment]
@dweymouth reminder that OS fields that are supported must not be omitted but returned with empty value so that clients know what the server support or not and can choose the appropriate fallback.

**Comment by dweymouth** [comment]
> @dweymouth reminder that OS fields that are supported must not be omitted but returned with empty value so that clients know what the server support or not and can choose the appropriate fallback.

I don't think this works for every field. We can certainly return an empty string for MBId for example but there's a difference between an unknown BPM and zero BPM (ambient/drone tracks have a legitimately 0 BPM). How do we handle this except omitting the field when it's unknown?

**Comment by Tolriq** [comment]
Well 0 BPM is a blank track, but it was discussed in the PR and is in the API and when I asked what cases do we need to define special default value I got no answer.

If you do not want 0 then -1 as not present is valid and we can amend the documentation for that field.

But the whole field additions without creating OS extensions is based on the principle that is a field is supported by a server it MUST be always returned so that client knows the server support it.

If we do not follow this simple rule then what have been done can be scrapped and we define extensions per field or group of fields or whatever suit best the servers.

**Comment by dweymouth** [comment]
Well it looks like Navidrome internally doesn't distinguish between 0 and missing BPM so I guess it'll be returning 0 for now. However I do think we should define -1 as a sentinel value for missing BPM since 0 technically is valid. (We could even do `bpm: -1` in JSON and `bpm=""` in XML but maybe that is too confusing.)

**Comment by dweymouth** [comment]
We also need to change `userRating` which is an OpenSubsonic field that Navidrome was returning anyway to be non-omitempty as well. I'll wait for Deluan's input to do anything since this is now a slightly larger change.

**Comment by Tolriq** [comment]
No problem for -1 we can amend the doc for that. No need for a tons of discussion.

**Comment by deluan** [comment]
Hey @dweymouth, based on the conversation, seems that we need to remove the `omitempty` tags from the new fields, is that right?

**Comment by dweymouth** [comment]
Yep, including from the existing `userRating` field for AlbumID3 which is not in the original Subsonic spec but that Navidrome was including anyway. I'll push that change this evening

**Comment by deluan** [comment]
Hey @dweymouth, snapshots tests are failing. Anyway, I see that when `genres` (an array) is empty, the response generated is `"genre": null`. I don't think that's what we want, right?

**Comment by dweymouth** [comment]
Looks like I need to regenerate the snapshots now that we have changed some fields to be non-omitempty. I am confused about why it is marshaling the `genres` array as `null` instead of empty though since I'm creating it even if it's zero-length in `itemGenresFromGenres`

**Comment by deluan** [comment]
> Looks like I need to regenerate the snapshots now that we have changed some fields to be non-omitempty. 

Yep

> I am confused about why it is marshaling the `genres` array as `null` instead of empty though since I'm creating it even if it's zero-length in `itemGenresFromGenres`

The snapshots are generated by creating structs inline. As this is a new way of instantiating the repsonse structs, it won't work anymore: https://github.com/navidrome/navidrome/blob/53607fe11446a1bac581bc551ba740456dd4720d/server/subsonic/responses/responses_test.go#L123

@Tolriq I'm not sure the value of adding the fields with zero-values to the response, if they are optional.

**Comment by Tolriq** [comment]
@deluan this was discussed many times during your absence in PR implementation, but this is because they are optional :)

We decided to not add named extensions for each and every fields that servers supports, but clients needs to know if a server support a field consistently to be able to take decision about what to do with the data that server can handle or not.

Returning empty fields is the only way to achieve that.

Returning empty genres is explicit the server support genres and there's none. Not returning the field, means the server does not support genres fall back to single field genre and try to apply split if the server does not handle genre split and everything.

**Comment by deluan** [comment]
Hey @dweymouth, to avoid having scattered logic to initialize the `genres`, `BPM` and other fields that may need a default value different than their zero-value, I think a cleaner approach would be to use a [custom marshaller](https://archive.li/nPyrH#selection-1549.0-1552.0:~:text=Method%201%3A%20Custom%20Marshaler) for these structs. What do you think?

**Comment by dweymouth** [comment]
I added custom marshalers for Child and AlbumID3 and the genres slice is no longer marshaling as nil, but the shapshots are still failing. How do I regenerate them with the new expected output?

**Comment by deluan** [comment]
> How do I regenerate them with the new expected output?

```
make snapshots
```

Check if the generated snapshots are valid before committing them.

**Comment by Tolriq** [comment]
@deluan any decision about https://github.com/opensubsonic/open-subsonic-api/pull/65 ? So that @dweymouth can put the proper value directly.

**Comment by dweymouth** [comment]
> @deluan any decision about [opensubsonic/open-subsonic-api#65](https://github.com/opensubsonic/open-subsonic-api/pull/65) ? So that @dweymouth can put the proper value directly.

Navidrome itself currently doesn't treat a missing BPM different from a 0 bpm internally. I also don't care *that* much about distinguishing them, and that OpenSubsonic PR uses **may** language anyway (ie it doesn't say a server *must* distinguish 0 BPM from missing). But when that lands to OpenSubsonic and I add BPM info to Supersonic, I will code it to display a 0 BPM value but display nothing for a negative BPM value.

**Comment by deluan** [comment]
To handle a 0-BPM different than no-BMP, it requires changes to the way this is handle in the DB and everywhere else. Do we really need to differentiate this? I understand 0-BPM is a valid value, but how often or common this is? Maybe spend too much time to handle an extra-edge case is not worth it...

**Comment by dweymouth** [comment]
> To handle a 0-BPM different than no-BMP, it requires changes to the way this is handle in the DB and everywhere else. Do we really need to differentiate this? I understand 0-BPM is a valid value, but how often or common this is? Maybe spend too much time to handle an extra-edge case is not worth it...

I agree - that's what I was getting at with my comment about the OpenSubsonic PR using *should* instead of *must*. It's giving servers that are able to distinguish 0 from missing a means of communicating it to the client, but doesn't require it

**Comment by deluan** [comment]
Let's keep it like this for now. And I'll keep in mind this when refactoring the DB to add more OpenSubsonic features.

**Comment by Tolriq** [comment]
@dweymouth you wanted the -1 :p I'm all for leaving 0 me, we can also drop the PR to set the default to -1.

**Comment by dweymouth** [comment]
I'm OK with server-specific implementation differences on that field too. I wanted to give servers who do distinguish missing from 0 the ability to pass that to the client. (So the client could display nothing instead of 0 in its BPM column for example).

Though server-specific implementations are what you're trying to avoid @Tolriq so I guess I'm also OK with scrapping that PR for now, and reopening it with *must* language if we can get *ALL* servers on board with it in the future.

**Comment by Tolriq** [comment]
Ok so closing that PR and waiting to decide for a must later then, makes more sense to be consistent as you say.

**Pull request merged**
