### PR TITLE
Refactor routing

### PR DESCRIPTION
**Pull request by deluan**
BREAKING CHANGE!

This is a preparation for allowing plugins to add new endpoints to Navidrome. As a result, the Native API routes were changed:
```
/app/login => /auth/login
/app/createAdmin => /auth/createAdmin
/app/api/* => /api/*
```
---
Hey @ajgon , I did some refactoring in the http routing code, and also changed a bit the code you contributed in #1152 

I don't have the setup required to test if the reverse proxy authentication is still working correctly. Can you please try this branch and let me know? Thanks!

### CODE REVIEW

**Comment by ajgon** [comment]
Works like a charm from start to finish :+1: 

I found one small issue though - for whatever reason, navidrome doesn't pick up `ND_REVERSEPROXYWHITELIST` environment variable for me. I had to configure `ReverseProxyWhitelist` manually in `navidrome.toml`. Shouldn't viper pick it up automagically, or did I miss something in my PR?

**Comment by deluan** [comment]
> Maybe because the whitelist header doesn't have `viper.SetDefault` stanza?

Yes, that was it. It's fixed now. Also, one of the things I wanted to test is removing the JWT token from the UI when the authentication is based on the request header. Can you try with the latest commits? Thanks again!

**Comment by ajgon** [comment]
Tested :)

Whitelist environment variable now works properly. Unfortunately, after removal of JWT token, I'm not able to auto-sign in anymore.

**Comment by deluan** [comment]
> Unfortunately, after removal of JWT token, I'm not able to auto-sign in anymore.

Ops, my bad. I was able to simulate it here (by injecting `remote-user` header using a middleware), and it seems to be working now. Can you confirm? Thanks!

**Comment by ajgon** [comment]
Works like a charm :)

**Pull request merged**
