### PR TITLE
Placement of Play next to the left

### PR DESCRIPTION
**Pull request by Dnouv**
As mentioned in issue #559 for better UX, the play next button was required to be moved on the left side. In this PR, there are edits in AlbumSongs.js to move the play next and other buttons to the left. Please refer to the screenshots for the new changes.
On mobile view
navid_uxp-sm

On medium-size display view
navid_uxp-md

Feedbacks are most welcomed. Thank you!

### CODE REVIEW

**Comment by deluan** [comment]
So, from what I understand from your screenshots, you only change the BulkActionsToolbar for medium-size displays and above, right?

Anyway, I don't think making it into two-lines is a good thing. It becomes too big and uses too much space.

**Comment by Dnouv** [comment]
Yeah, @deluan, I thought on medium-size displays, maybe we could allow some extra column space, so what are your reviews? Shall we place all the play buttons on the left and the "1 Item selected" dialog on the right? That way, it will be on a single line.

**Comment by Dnouv** [comment]
@deluan, I understand you may be busy, but I will truly appreciate it if you could provide feedback on this.
Thank you!

**Comment by deluan** [comment]
>  Shall we place all the play buttons on the left and the "1 Item selected" dialog on the right? That way, it will be on a single line.

Can you try this? Or if you have any other suggestion, let me know.

**Comment by Dnouv** [comment]
@deluan, here are the changes after swapping the play switches and "item selected."
navid559

Another possible solution would be keeping it of two lines but decreasing the above and below blue margins; that way, it may occupy less space while staying in two lines; what would you suggest?
Thank you for your review!

**Comment by deluan** [comment]
Hey @Dnouv, sorry but I'm don't feel the end result is an improvement.... I think we should leave like it is, unless you (or someone) comes up with a great design that is compatible with React Admin and requires as few changes as possible.

**Comment by Dnouv** [comment]
No worries, @deluan, I will discuss new ideas whenever I get one; thanks for your review.

**Comment by Himanshunitrr** [comment]
Was going through issue https://github.com/navidrome/navidrome/issues/559. I don't think that selecting classname as you have selected is the correct way(that name comes in dev tools inspector after a lot of processes). @deluan sir, what's your opinion?

**Comment by Dnouv** [comment]
@deluan, how about this design there was an empty space, near above the select box, so the items selected could be placed there 
image

**Comment by deluan** [comment]
This looks better :) Just have to see the effect of having 100+ items selected and how this will affect the alignment of the checkboxes, specially in smaller resolutions

**Comment by Dnouv** [comment]
Yeah, I have tested it for different screen sizes; it works perfectly, though not a suitable option for mobile screens; I forgot to test the case for 4 digits items; however, it works fine up to 1000 items.

**Comment by deluan** [comment]
I think you forgot to push.... Also, if this is better, we would want to do the same for **all** Datagrids, for consistency. Maybe it is better to create a common/Datagrid.js that implements this and can be used elsewhere, without replicating this change all over the place

**Comment by Dnouv** [comment]
Ok, I would make the required changes and push it. Thanks for your review.

**Comment by Dnouv** [comment]
@deluan, the previous idea about only showing the numbers near the checkbox did not give positive results, so here is a new idea the Bulkactions toolbar buttons will be the same as default but whenever a user hovers on the Toolbar the "Items selected" and play button positions are swapped, here are the screenshots of the changes,
Before hover:
image

After hover:
image

Feedbacks are most welcomed. Thank you!

**Comment by Sohalt** [comment]
> @deluan, how about this design there was an empty space, near above the select box, so the items selected could be placed there image

What about replacing the checkbox to "select all", next to the selected count, with the `x` that's currently on the left? That would give the count a little room to breathe (and also work with 4 digits) and would still be consistent in behavior. The `x` removes the current selection and the checkbox selects all.

**Comment by Dnouv** [comment]
Thank you for the suggestion, @Sohalt; it's indeed quite a good idea. But I guess that would create unnecessary conflicts while updating the React-admin to a newer version. It would be better to incorporate these changes directly in the RA instead of customizing it here in Navidrome.
Please feel free to comment. Thank you!

**Comment by deluan** [comment]
Hey @Dnouv, I'm closing this as I'll need to rewrite the UI with the new React-Admin version (v4) and will try to implement this in a different way. Thanks anyway for the contribution!

**Pull request closed without merging**
