### PR TITLE
Add theme import theme Electric Purple

### PR DESCRIPTION
**Pull request by william-lohan**
Add theme import theme Electric Purple

### CODE REVIEW

**Comment by deluan** [comment]
Nice, can we have some screenshots, please?

**Comment by william-lohan** [comment]
image
image

**Comment by deluan** [comment]
Did you also changed the player? You can override its colors with some CSS hacking. See https://github.com/navidrome/navidrome/blob/master/ui/src/themes/dark.css.js#L8 for an example, on how we changed the player's default green color to blue.

Also, can you please rebase this PR with the latest from master?

**Comment by william-lohan** [comment]
rebased and added player css

image

**Comment by deluan** [comment]
Thanks!

**Pull request merged**
