### PR TITLE
Multiple artist support

### PR DESCRIPTION
**Pull request by certuna**
Closes https://github.com/navidrome/navidrome/issues/238 and https://github.com/navidrome/navidrome/issues/277

Adds support for multiple artists. There are three commonly used methods to tag these, this PR support all three:

1. Using the official multi-artist support in tags: null-separated strings in id3v2.4 (`Jay-Z<null>Kanye West`), multiple ARTIST fields in FLAC/MP4 (ARTIST = `Jay-Z`, ARTIST = `Kanye West`)
2. Single string with non-standard separator, usually semicolon: ARTIST = `Jay-Z;Kanye West`
3. ARTISTS/ARTIST method used by MusicBrainz Picard: multi-valued ARTISTS (`Jay-Z<null>Kanye West`), singlevalued ARTIST (`Jay-Z & Kanye West`) for backwards compatibility

How this PR works in the Navidrome DB `mediafile` and `album` tables:
- `artist` and `album_artist` are formed by concatenating multiple artists: `Jay-Z · Kanye West`
- `artist_id` is populated with the id of the first artist `0e37575446e8659caa9f2a3e298afc86`, i.e. clicking on `Jay-Z · Kanye West` will take you to the artist page of `Jay-Z`
- `all_artist_ids` has the ids of all artists: `0e37575446e8659caa9f2a3e298afc86 0b48849166b97b6b053a0e1e5e131231`, this makes the songs/albums show up in the artist discography
- all artist names added to `full_text`, so available for search

Three new config options (we can drop some of them if we deem them good enough to stay enabled all the time):
- `Scanner.MultipleArtists` (default `true`): if `false`, only the first artist in the tags is used.
- `Scanner.ArtistSeparators` (default `;`): just like `Scanner.GenreSeparators`
- `Scanner.RemixerToArtist` (default `true`): this does what Spotify does: reads the Remixer tag and treats it as an additional Artist.

I've been testing this for over three months now, it's pretty solid. Open issues:

### Dependencies/conflicts
[ Artist discography sorted own-albums-first #2580 ](https://github.com/navidrome/navidrome/pull/2580) is not strictly necessary but if we don't do it the discographies of artists with lots of compilation tracks and guest appearances/collabs will become a mess
[ Create artist objects for non-Album Artists #2583 ](https://github.com/navidrome/navidrome/pull/2583) is not strictly necessary but allows users to browse artists that have no albums but a lot of compilation tracks or guest appearances/collabs
[ Split albums by MusicBrainz Album ID #2538 ](https://github.com/navidrome/navidrome/pull/2538) is independent but conflicts with one line in `scanner/mapping.go`
[  refactor GetFullText() #2587  ](https://github.com/navidrome/navidrome/pull/2587) is independent but has conflicts

### Subsonic clients
Mainly around "Go to {track artist}" functionality, where you can navigate to the artist of a song. None of them are showstoppers in my opinion. I've been cross-referencing the behaviour with [LMS](https://github.com/epoupon/lms), another Subsonic server that supports multiple artists.
- **Substreamer:** works as expected, with s small cosmetic hiccup:if you Go To Artist `Jay-Z · Kanye West`, it takes you to Jay-Z's discography, but still displays the `Jay-Z · Kanye West` artist name - probably only needs a small fix on the Substreamer side to refresh the artist name after the clickthrough. For comparison, LMS does not provide an ArtistID for tracks with multiple artists, so Go To Artist isn't possible at all
- **Play:Sub:** Go To Artist gives an error, with both Navidrome and LMS. Seems it doesn't use the ArtistID, but does a lookup for up the Artist Name `Jay-Z · Kanye West`, which fails in both cases
- **Amperfy:** It displays the first artist, so it looks like it split on the middle dot clients side. Go To Artist works correctly, without errors. For comparison: when clicking Go To Artist, LMS gives API Error but does seem to load the discography.
- **Supersonic:** no issues
- **Sonixd:** no issues
- **Feishin:** no issues
- **Other subsonic clients?**

### Web UI Cosmetics
Since the artistID of the track only links to the first artist, clicking on the `Jay-Z · Kanye West` link in the WebUI will always take you to the artist page of `Jay-Z`, ideally the WebUI would make this clearer to the user by only hyperlinking Jay-Z, not the other artists. It's mainly cosmetic, but if we dislike it enough, someone with more JavaScript skills than me would have to take a look a this. At the moment this PR is 100% serverside.

Screenshot 2023-06-16 at 14 08 49

### CODE REVIEW

**Comment by Rycia** [comment]
As a user, just adding that I've been looking for this support for months and would like this pushed to main branch.

**Comment by dweymouth** [comment]
The OpenSubsonic org has recently finalized a Subsonic API extension for multi-valued artists (and genres) - perhaps we can add the OpenSubsonic support for this as well? https://github.com/opensubsonic/open-subsonic-api/pull/51

**Comment by certuna** [comment]
> The OpenSubsonic org has recently finalized a Subsonic API extension for multi-valued artists (and genres) - perhaps we can add the OpenSubsonic support for this as well? [opensubsonic/open-subsonic-api#51](https://github.com/opensubsonic/open-subsonic-api/pull/51)

Yes this is awesome news - let me check if I can add it in this PR.

**Comment by certuna** [comment]
Cleaned it all up, ready to merge I think.

**Comment by RubenTeixeira** [comment]
Hey @certuna , thanks for your work.

I'm getting this when using this PR:

`Nov 12 22:47:35 raspberrypi navidrome[16356]: time="2023-11-12T22:47:35Z" level=fatal msg="Failed to apply new migrations" error="error: found 1 missing migrations:\n\tversion 20230615000000: /github/workspace/db/migration/20230615000000_add_all_artist_ids_to_mediafile.go"`

What is missing?

**Comment by certuna** [comment]
> Hey @certuna , thanks for your work.
> 
> I'm getting this when using this PR:
> 
> `Nov 12 22:47:35 raspberrypi navidrome[16356]: time="2023-11-12T22:47:35Z" level=fatal msg="Failed to apply new migrations" error="error: found 1 missing migrations:\n\tversion 20230615000000: /github/workspace/db/migration/20230615000000_add_all_artist_ids_to_mediafile.go"`
> 
> What is missing?

Ah yes I'll fix this, there have been new additions to the codebase so my migration is outdated.

**Comment by RubenTeixeira** [comment]
> Ah yes I'll fix this, there have been new additions to the codebase so my migration is outdated.

Thank you so much! Looking forward to trying it out :)

**Comment by certuna** [comment]
> > Ah yes I'll fix this, there have been new additions to the codebase so my migration is outdated.
> 
> Thank you so much! Looking forward to trying it out :)

Should work now. I don't know if this PR will be merged soon or if we wait until we can do it all together with OpenSubsonic API support.

**Comment by RubenTeixeira** [comment]
> Should work now. I don't know if this PR will be merged soon or if we wait until we can do it all together with OpenSubsonic API support.

Yes it does! Looking good. Will keep happily testing and report if I find any incident.
Yeah I'm very excited for all the OpenSubsonic stuff. Can't wait :)

**Comment by tty228** [comment]
The number of tracks for each individual singer in a choir cannot be displayed correctly at the moment. This issue is likely related to the fact that the artistID of a track is only linked to the first artist. Additionally, it would be great if hyperlinks could be selected for ensemble singers.

**Comment by TacoCake** [comment]
Hey, what's holding this PR back? Does it still need contributions?

**Comment by RubenTeixeira** [comment]
> Hey, what's holding this PR back? Does it still need contributions?

Perhaps it's the fact that the author did not prepare support for OpenSubSonic API. It works great otherwise. I'm also looking forward for this.

**Comment by dweymouth** [comment]
> Hey, what's holding this PR back? Does it still need contributions?

From conversations on Discord it's that this PR kind of "hacks" around the existing DB schema, whereas Deluan now prefers to redesign the database schema "properly" for the many-to-many relationships between artists and albums. So this PR will likely get scrapped in favor of a larger-scale database redesign. But this is a good thing as doing it right at the database level will probably be more performant and enable future extensions more easily.

**Comment by TacoCake** [comment]
> > Hey, what's holding this PR back? Does it still need contributions?
> 
> From conversations on Discord it's that this PR kind of "hacks" around the existing DB schema, whereas Deluan now prefers to redesign the database schema "properly" for the many-to-many relationships between artists and albums. So this PR will likely get scrapped in favor of a larger-scale database redesign. But this is a good thing as doing it right at the database level will probably be more performant and enable future extensions more easily.

Ah, I see, thanks for the info. Is there anywhere I can track this?

**Comment by deluan** [comment]
> Ah, I see, thanks for the info. Is there anywhere I can track this?

@TacoCake: #2709

**Pull request closed without merging**
