### PR TITLE
Work/Movement/Subtitle support

### PR DESCRIPTION
**Pull request by certuna**
First step towards https://github.com/navidrome/navidrome/issues/279

Server-side:
- reads W/M/S tags
- inserts in DB
- includes in `song` API endpoint

Web UI:
- displays W/M/S in album tracklist, playlist and songs list
- displays M in now playing/play queue/browser tab

remaining issues to be fixed:
- album tracklist: don't display a Work row if Work = empty
- playlist & songs list view: never display a Work row
- playlist & songs list view: sorting on Title sorts on Title, not Movement

### CODE REVIEW

**Comment by certuna** [comment]
btw in SongTitleField.js, I'm using dropWork, I could just as easily have used showWork, but is there some good coding practice that you should never use negative variables?

**Comment by deluan** [comment]
Please format it with prettier, by running `cd ui && npm run prettier`. Thanks

**Comment by certuna** [comment]
> Please format it with prettier, by running `cd ui && npm run prettier`. Thanks

Done, but the romanize function in SongTitleField.js now looks a bit bad.

**Review by deluan — COMMENTED** [review]
Looks good overall, I'll remove the duplication before merging. A couple of comments, though:
1) Please regenerate the migration file using the command: `make migration name="add_work_movement"`. 
2) We may need to add indexes to these new columns, if they will be listed as column options in any song grid
3) You didn't create the `display_title` as we discussed in Discord, right? I think we should do it before merging

EDIT: By the way, it is still failing in prettier check for file `src/audioplayer/AudioTitle.js`

**Comment by certuna** [comment]
1. I get an error `make: *** [migration] Error 1`
2. Only Work will be a new column option in the Song grid - how/where do I index it?
3. I'd like to have a bit more discussion before I add `display_title`, since I think we can do correct sorting in the SQL query for the `song` endpoint rather than create a whole new column in the `mediafile` table.
4. fixed

**Pull request closed without merging**
