### PR TITLE
Restart Current Song on previous

### LINKED ISSUE #652: Previous Track button does not restart the current track
I know that this is probably behaving as intended, but 95% of players implement this button such that it will first restart playback of the currently playing track from the beginning rather than going strait to the previous track.

### PR DESCRIPTION
**Pull request by aniketbiswas21**
Fixes #652

https://user-images.githubusercontent.com/51146347/117529968-5eabce00-aff8-11eb-81b8-9aedd01e7ad3.mp4

Restarts the current song on selecting the previous button, if the audio time of the current song is greater than `1`, else plays the previous song.

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@deluan Please take a look :smile:

**Comment by deluan** [comment]
Thanks for the work on this. I'll upgrade the player in a different commit, so we can make this change separated from the upgrade, as it also fixes other issues and may bring new ones. Will upgrade it this weekend

**Comment by aniketbiswas21** [comment]
> Thanks for the work on this. I'll upgrade the player in a different commit, so we can make this change separated from the upgrade, as it also fixes other issues and may bring new ones. Will upgrade it this weekend

 :+1:

**Comment by deluan** [comment]
Upgrade done. Please rebase and I'll merge this

**Comment by aniketbiswas21** [comment]
> Upgrade done. Please rebase and I'll merge this

Done :+1:

**Comment by aniketbiswas21** [comment]
I accepted all the incoming changes. But, the package.lock is  still showing up in the commit :sweat:

**Comment by aniketbiswas21** [comment]
> @deluan I accepted all the incoming changes. But, the package.lock is still showing up in the commit

Fixed it :sweat_smile:

**Pull request merged**
