### PR TITLE
Add `/` to `_` mapping for file tags.

### LINKED ISSUE #592: MP3 will not play in Dsub if song title tag contains "/"
The songs will play in Navidrome's web UI but not to Dsub. I believe this is a Navidrome issue as the same songs will play to Dsub from Airsonic.

### PR DESCRIPTION
**Pull request by YashJipkate**
Add `/` to `_` mapping for song tags so that it becomes playable in subsonic clients.
Fix #592.

### CODE REVIEW

**Comment by deluan** [comment]
Did you test this? What happens in DSub when you cache a few songs with `/` in their names and then put it in offline mode? Can you see the files with `_` instead of `/`?

**Comment by YashJipkate** [comment]
Yes I tested it. Sorry, I forgot to add the samples, even had them ready actually. Here is a screen recording of the DSub. 

https://user-images.githubusercontent.com/34203227/112097271-b5cf1e00-8bc5-11eb-99e1-f2c101ba1018.mp4

This is the path of the song as sent in response to `getSong`
```
"path": "_ Olive B _/Olive__album/Play _ Mate.mp3",
```

Please take a look.

**Comment by deluan** [comment]
Thanks, will do more testing on my local before merging.

**Comment by deluan** [comment]
LGTM. Thanks!

**Pull request merged**
