### PR TITLE
Fixes #639 - Added Ratings feature to Album, Artist and Song 

### LINKED ISSUE #639: Ratings in local UI?
First of all, thank you very much for this app! It's been very responsive on my Pi-based server, unlike other ones I've tried.

I'm moving from desktop-hosted content to my server and I'm hoping to get as close to what I'm used to as possible.

I've been using Banshee as a player and I've gotten used to two things: 1) smart playlists (which I see in another ticket that you're planning on implementing [yay!]) and 2) ratings (0-5).

I see in the subsonic code that you support both stars and ratings, but it seems like the local UI only supports stars. Is there a plan to include (or enable by config) ratings?

Thanks again.

### PR DESCRIPTION
**Pull request by neilchauhan2**
album-l
album-s
albumlist-l
albumlist-s
song-l
song-s
artist-l
artist-s

#### Added Rating Feature to the following components: 
- AlbumGridView.js
- AlbumDetails.js
- AlbumListView.js
- ArtistList.js
- SongList.js
#### Added the setRating method in the subsonic directory. 

This PR fixes #639

### CODE REVIEW

**Comment by TheFlatworm** [comment]
Will this be electable in the UI - to turn feature on/off. Do not like to rate albums or songs.

**Comment by neilchauhan2** [comment]
@TheFlatworm the update with this PR doesn't support the feature to turn on/off the ratings in the UI.

**Comment by deluan** [comment]
Hey @neilchauhan2 , thanks for the PR! Now that I was able to think through the whole feature, here are my thoughts on it:

- We will need to refactor the current "Star" to "Love" and change the icon from ⭐️ to ❤️, as you correctly pointed out in your comment in the issue.
- As @TheFlatworm said, before adding 5-star ratings to the UI, we will need to add options to enable/disable one or both of the rating systems. We may need to do this and the refactor above before introducing a 5-star rating, or the Ui will be too confusing.
- Your 5-star component has some issues: It cannot be reset (no star), and it breaks in some situations. Example:
Screen Shot 2021-03-21 at 8 10 25 PM

- Instead of creating your own component, you should leverage the one provided by Material-UI: https://material-ui.com/components/rating/#customized-ratings . It also solves the issues above. I personally like the "Custom empty icon" variation, it is less noisy
- Speaking of noisy, the component needs to be more subtle, less "in your face". Similar to how the single Star icon works today: It only shows in the songs and album covers if you hover over the context menu. For albums we should not even show it, it could be an option in the context menu. I think a really good implementation is how Apple Music/iTunes works, here are some screen captures:


ezgif com-gif-maker (2)


ezgif com-gif-maker (1)

- The issue with calling `setRating` for Artist, it seems to be a bug on the backend. I will take a look.


If you wanna proceed with this feature, let me know in Discord and we can chat about it.

**Comment by neilchauhan2** [comment]
@deluan I would definitely love to proceed with this feature, and make the required improvements in order to have a better User experience for Navidrome. Yes, lets move the discussion about this to discord.

**Comment by neilchauhan2** [comment]
@deluan Should I start off with removing the current **Rating Components** that I have created and instead use the **Material UI Rating component** that you have mentioned in the above comments, once I'm done with **Refactoring the Star to Love Icon**?
Secondly, I understand that by refactoring the **Star** to **Love** component, you only mean changing the icon. Is that the case? Because, just by changing the icon from Star to Love things will automatically get better. 
Lastly, I would like that you mention any other details that are relevant to this feature, and help me with some guidance about the approach. I'm targeting to finish off this feature by the end of this week if all goes well.

**Comment by deluan** [comment]
> Secondly, I understand that by refactoring the **Star** to **Love** component, you only mean changing the icon. Is that the case? Because, just by changing the icon from Star to Love things will automatically get better.

The refactor is a bit more complicated: We also need to change the text and all translations. So we should add new translation keys (`love`?) and stop referencing the old key. It is better to not have it translated instead of displaying "Star" on a Heart icon.

The part that is more complicated is the preference to enable/disable one or both rating systems. Currently there's no support for storing this using the API. We may take a shortcut and introduce config options that disable/enable them at a global level, instead of per user, and later add this. 

Also, disabling the star/heart when could be trick as it may break the layout.

For now, create two options in the `config.js` file: `enableFavourites` and `enableStarRating`, and check if they are enabled before rendering

We can chat more in Discord, if you still have questions.

**Comment by neilchauhan2** [comment]
@deluan I'll work on the `enableFavourites` and `enableStarRating` options in the `config.js` right now and let you know once I'm done with figuring out the rendering based upon these options.

**Pull request closed without merging**
