### PR TITLE
Adds a Monokai theme

### PR DESCRIPTION
**Pull request by chief8192**

### CODE REVIEW

**Comment by deluan** [comment]
Nice! Can we have some screenshots, please?

**Comment by deluan** [comment]
Never mind, tried it locally, works great. Thanks for the contribution.

**Comment by chief8192** [comment]
Ahh, beat me to it, was just about to post [these](https://imgur.com/a/ouC0E7Y). Found a glitch with the error popup in the process though, I'll send along another PR.

**Comment by deluan** [comment]
Adding the screenshots here, for future reference.

Nf9A6Kf
9BmPtpr
q9Aixx6

**Pull request merged**
