### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by deeeeeebs**

### CODE REVIEW

**Comment by deluan** [comment]
Hey @deeeeeebs , thanks for this! I see there are two variants of the language: Swedish and Swedish (FI). I'm assuming the later is for Finland, right? To which one does your translation applies?

Do you want to join the translation project in POEditor? If you want, please join our Discord server, #translations channel.

**Review by deluan — COMMENTED** [review]
The ISO 639-1 code for Swedish is `sv`: https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=sv

Any reason why you used `se`?

**Comment by deeeeeebs** [comment]
Hey @deluan!
I'm totally fresh to github so sorry if mistakes are made...

Swedish (FI) is for Finland yeah. This translation is for Swedish and you are absolutely right, the code should be sv and not se. Was about to type sv but for whatever reason, I thought it was se going by earlier projects i've translated years ago and didn't bother to check the ISO standard.

**Comment by deluan** [comment]
No worries. For testing purposes, you can put your translation file in the `${DataFolder}/resources/i18n` folder, restart Navidrome and you will be able to select the language after refreshing the browser.

Please check if everything is correct, fix any pending issue if any, including the change from `se` to `sv`. Once that's done, I can merge it to master.

**Comment by deeeeeebs** [comment]
Tried to look for this earlier before I submitted and sorry if it's a dumb question but where do I find the data folder?

My current install is on Debian buster and there are only 2 folder locations with data in them from what I can tell
**/var/lib/navidrome** (which only has a cache folder and some database files)
and
**/opt/navidrome** (which has the navidrome executable, license and readme + the music folder)

**Comment by deluan** [comment]
Thanks! Please consider joining Discord, it is easier to keep translators informed about new terms being introduced.

**Pull request merged**
