### PR TITLE
Make spotify-ish more spotify-ish

### PR DESCRIPTION
**Pull request by samarsault**
I've introduced some possible overrides like `NDAlbumGridView`, `NDAlbumDetails` etc. to make theming much more flexible.

I'm trying to modify the player as well, but overriding audioTitle (from below), after assigning a class doesn't seem to work.
https://github.com/navidrome/navidrome/blob/01ba00ccdd3b98248ffef8bfb59bdc43a873d693/ui/src/audioplayer/Player.js#L24-L35

### CODE REVIEW

**Comment by samarsault** [comment]
Screenshot 2021-03-27 at 12 43 05 AM
Screenshot 2021-03-27 at 12 43 05 AM
Screenshot 2021-03-27 at 12 46 04 AM

**Review by deluan — COMMENTED** [review]
Thanks, this is really cool! I really liked it! But there are still some rough edges/concerns:

- Too much code change, and it is not always clear why... Themes should be contained in their theme.js files (unless you are trying to introduce more customization without breaking other themes)
- Play buttons on the album cover are green, but not the Star or the Context Menu
- Too much space between these buttons:
Screen Shot 2021-03-26 at 10 31 02 PM
- Maybe we could [change the colour](https://stackoverflow.com/questions/7415872/change-color-of-png-image-via-css) of the album cover placeholders with CSS, to match the theme?

By the way, I fixed the colour of the `audioTitle`, please rebase from master

**Comment by samarsault** [comment]
@deluan I think the major code changes are from https://github.com/navidrome/navidrome/pull/914/commits/a77c5485a4ef3f5e6790c74a97bedc83823d5677 which were added when I rebased and prettier fixes to them. 

Rest of the changes are named classes (for greater customization) and in the theme file.
I'll rebase with master and fix that.

**Comment by samarsault** [comment]
> * Play buttons on the album cover are green, but not the Star or the Context Menu

That has been deliberately, as per spotify's design

**Comment by samarsault** [comment]
> * Too much space between these buttons:

This has been fixed

**Comment by samarsault** [comment]
> * Maybe we could [change the colour](https://stackoverflow.com/questions/7415872/change-color-of-png-image-via-css) of the album cover placeholders with CSS, to match the theme?

Yeah, I had thought about it. But this would involve some code change since we don't have access to to the image url.

**Comment by samarsault** [comment]
[Updated preview]

Screenshot 2021-03-27 at 8 11 45 PM

Screenshot 2021-03-27 at 8 12 08 PM

**Comment by deluan** [comment]
> Rest of the changes are named classes (for greater customization) and in the theme file.

Yeah, GH's diff is too noisy, but your changes are very important!

> Yeah, I had thought about it. But this would involve some code change since we don't have access to to the image url.

That's fine, we can work on that later, if you want to improve the theme even further. Being able to style the cover placeholder would be really cool.

I checked out the code in my local, and even though the theme looks awesome, it still has some rough edges:

- We should have at least a small gap between the two buttons, to make it clear they are two separated buttons. But I'm not a UX/UI person, so I trust your judgment on this.
Screen Shot 2021-03-27 at 11 46 33 AM

- Almost all views in mobile now have issues with responsiveness:
ezgif com-gif-maker (3)

**Comment by samarsault** [comment]
> * We should have at least a small gap between the two buttons, to make it clear they are two separated buttons. But I'm not a UX/UI person, so I trust your judgment on this.
Yeah, there should be some level of contrast. 


> * Almost all views in mobile now have issues with responsiveness
Yeah, noticed that. It might be because of changes in spacing everywhere. Looking into it.

**Comment by deluan** [comment]
Forgot to mention: the play button in the mobile view is also too big. I'm not near my computer to add a screenshot, but please look into that

**Comment by Dnouv** [comment]
Hey @samarsault, how about adding a red fill color in the heart icon instead of white? @deluan, what are your opinions? Wouldn't it be nice?

**Comment by samarsault** [comment]
> Hey @samarsault, how about adding a red fill color in the heart icon instead of white? @deluan, what are your opinions? Wouldn't it be nice?

Nice idea, however, I don't think the red would go along well with the rest of the spotify-ish interface.

**Comment by samarsault** [comment]
I've contrasted the two buttons(toggle grid/list) and have fixed the responsive issues I could find.
Let me know if you spot any more.

**Updated look**

Screenshot 2021-03-28 at 4 54 12 PM

Screenshot 2021-03-28 at 4 56 54 PM

**Comment by deluan** [comment]
Looks better! I'll do more testing later. One note though: I'm not 100% ok with the mode selector:
Screen Shot 2021-03-28 at 1 02 15 PM

Maybe put the "unselected" one in a darker green? Making it the same colour as the background looks weird IMHO....

**Comment by samarsault** [comment]
> Maybe put the "unselected" one in a darker green? Making it the same colour as the background looks weird IMHO....

Agreed, changing it.

**Comment by samarsault** [comment]
Added some contrast in there:
Screenshot 2021-03-29 at 4 26 35 PM

**Comment by deluan** [comment]
Yes, it is better, but I still see some issues with the responsiveness of the Album Grid:
Screen Shot 2021-03-29 at 10 24 48 PM

Also, in the screenshot you can see that the "Add Filter" and the "Album List mode" buttons still have the old styling (and also in other views). Did you forgot about it, or it is the intended behaviour?

**Comment by samarsault** [comment]
> Yes, it is better, but I still see some issues with the responsiveness of the Album Grid:

What screen size is this? I can't reproduce it.

> Also, in the screenshot you can see that the "Add Filter" and the "Album List mode" buttons still have the old styling (and also in other views). Did you forgot about it, or it is the intended behaviour?

Yeah, this was intended. Any thoughts?

**Comment by samarsault** [comment]
> "iPhone X" option in Chrome's device bar (running on macOS). 375x812
> 
> >

Looks fine on my system:
Screenshot 2021-03-30 at 9 42 23 PM

**Comment by samarsault** [comment]
Login page:
Screenshot 2021-03-30 at 10 33 15 PM

**Comment by deluan** [comment]
> Looks fine on my system:

Mine is 100%, yours is 75%.....  Also, the issue may be related to this: #647

(Nice login page :)

**Comment by samarsault** [comment]
Fixed pagination:

Screenshot 2021-03-31 at 11 21 34 PM

**Comment by deluan** [comment]
Merging! Thanks a lot for your patience in getting this fine-tuned!

**Comment by ryansalerno** [comment]
If you want to play with the record color without completely redoing the code for it, you can `filter: hue-rotate(270deg);` on the `img` and get pretty far.... I don't think matching the button hex is the best idea since it'll blend with the play button, but you could encourage themes to pick some semi-complimentary color instead of Navidrome blue.

**Pull request merged**
