### PR TITLE
style(SongDataGrid): Improved Header Readability - #943

### LINKED ISSUE #943: Album's Song List Rearrangement
When an album is selected and the songs are displayed the title bar above the song list looks to be part of the list itself:

Screen Shot 2021-03-29 at 1 52 47 PM

Could this be redesigned to separate the header more clearly - something  like this:

Screen Shot 2021-03-29 at 2 10 50 PM

### PR DESCRIPTION
**Pull request by Balaguru4580**
Closes #943 issue of the header row being visually too similar to the song rows.

Description: Improves visual distinction of the the header row for table for readability.

Changes: The Header Cell titles have all been set to bold and the Header Row is now distinctly more spaced out to improve visibility.

### CODE REVIEW

**Comment by deluan** [comment]
Screenshots would be awesome :)

**Comment by Balaguru4580** [comment]
Screenshots for the base design here.
Screenshot_2021-03-31 Navidrome(2)
Screenshot_2021-03-31 Navidrome

**Comment by certuna** [comment]
I like this look, yeah.

**Comment by certuna** [comment]
Although to be honest we could probably hide the "#" and "Time" headers since it's very obvious what these columns mean :)

**Comment by Balaguru4580** [comment]
I do agree, but I feel the # numbers would look a bit odd without a title. Especially in cases like in the screenshot where it doesn't have an order.

**Comment by deluan** [comment]
@Balaguru4580 Thanks for this. Can you please rebase it from master, to remove commits that were not created by you?

@certuna Without a title you cannot click on it to sort by that column....

**Comment by Balaguru4580** [comment]
Rebase Complete. Also, here's the updated design. Added a boxshadow instead of a transparent borderline for better compatibility with the white theme.

**Comment by deluan** [comment]
LGTM, thanks!

**Pull request merged**
