### PR TITLE
Parse more itunes keys

### LINKED ISSUE #2679: [Bug]: ReplainGain on some M4A files not detected
### I confirm that:

- [X] I have searched the existing [open AND closed issues](https://github.com/navidrome/navidrome/issues?q=is%3Aissue) to see if an issue already exists for the bug I've encountered
- [X] I'm using the latest version (your issue may have been fixed already)

### Version

0.50.1

### Current Behavior

The replay gain of some M4A files is not detected. 

This seems to the case when the name of the corresponding tag (REPLAYGAIN_TRACK_GAIN) is in all uppercase instead of all lowercase. As an example, the application [rsgain](https://github.com/complexlogic/rsgain) creates the tags with names that are all uppercase, and so does the application MusicBrainz Picard.

### Expected Behavior

The replay gain is correctly detected, as stored in the metadata of the M4A file.

### Steps To Reproduce

1. Run Navidrome 0.50.1 with its default settings.
2. Add the test audio files from [testdata.zip](https://github.com/navidrome/navidrome/files/13537841/testdata.zip) to the music library.
3. Login to the Navidrome UI and perform a full scan.
4. Check the details of the two tracks using the _Get Info_ context menu. The track _Working_ has the correct track replay gain (-6.1 dB). the track _Not Working_ has an incorrect track replay gain (0 dB).

### Environment

```markdown
- OS: Ubuntu 22.04
- Browser: Firefox 120.0
- Client: Navidrome UI
```

### How Navidrome is installed?

Docker

### Configuration

_No response_

### Relevant log output

```shell
time="2023-12-03T02:04:06Z" level=trace msg="TagLib: read tags" filename=/music/notworking.m4a id=0 tags="map[bitrate:[192] channels:[2] date:[2023-12-03 2023] duration:[1] encodedby:[Lavf58.76.100] lengthinmilliseconds:[1000] title:[Not Working Not Working]]"
time="2023-12-03T02:04:06Z" level=trace msg="TagLib: read tags" filename=/music/working.m4a id=1 tags="map[bitrate:[192] channels:[2] date:[2023-12-03 2023] duration:[1] encodedby:[Lavf58.76.100] lengthinmilliseconds:[1000] replaygain_track_gain:[-6.10 dB] title:[Working Working]]"
```

### Anything else?

The solutions seems trivial, I might create a pull request.

### Code of Conduct

- [X] I agree to follow Navidrome's Code of Conduct

### PR DESCRIPTION
**Pull request by kgarner7**
Seeks to resolve #2679 (and parse additional tags as well). I'm not confident in the C++ change, so please review. Both `.m4a` files have an empty key `----:com.apple.iTunes:`, and the new `test.m4a` has uppercase ReplayGain keys.

### CODE REVIEW

**Comment by marksdestiny** [comment]
I tested the binaries. It seems to load the metadata for my M4A files correctly, resolving the issue #2679. Thanks.

**Comment by deluan** [comment]
@kgarner7 I did some simplifications in the C++ code, moving some of the logic to the Go wrapper. C++ is harder to maintain and easier to insert memory leaks. Let me know what do you think.

**Comment by certuna** [comment]
This patch also solves https://github.com/navidrome/navidrome/issues/2674 , awesome!

**Comment by deluan** [comment]
> https://github.com/kgarner7/navidrome/tree/m4a-separate is more what I was thinking of...

I see. But I don't think a simple char check will have impact on performance, and the final result is simpler. My main goals with this wrapper are: first, as little and simple code as possible in C++, second is performance and memory utilization. 

So, the more C++ code I can remove the better, even if it sacrifices a bit the Go implementation. In you implementation, you need to call strdup/free a couple of times more, increasing the surface for potential memory leaks.

**Pull request merged**
