### PR TITLE
Use Workbox as a npm module

### LINKED ISSUE #1147: Navidrome connects to google
### Description

I noticed that navidrome is asking my browser to connect to `https://storage.googleapis.com/workbox-cdn/releases/6.1.2/workbox-sw.js`. It is the only remote resource that's fetched.

I blocked `storage.googleapis.com` in ublock and found that navidrome is still working as expected. So my question would be:

* Is workbox needed at all or can it be removed?
* If it's needed, would it be possible to include this js lib in navidrome instead of loading it from google?

I'm using navidrome version 0.42.1.

### PR DESCRIPTION
**Pull request by deluan**
EDIT: NOT WORKING!

Fixes #1147

### CODE REVIEW

**Comment by Dnouv** [comment]
@deluan, I was trying to tackle this issue, but how do we test service worker in the local development environment, I was able to see service workers on the demo site under DeveloperTools>Applications>ServiceWorkers, but there was no service worker on `localhost:4633`. Could you please help me out with this issue? Thank you!

**Comment by certuna** [comment]
That's interesting, I'm just checking this under Firefox and Chrome (macOS) and both do load the service worker for `http://localhost:4533` ("status: activated and is running"), this is with ND 0.43. What OS are you using?

**Comment by Dnouv** [comment]
Thanks, @certuna for a prompt reply; I have a development setup in Chrome(on windows WSL), here is the screenshot of both the demo site(on the left side) and `localhost:4533`(right side of image),
image
I am running the ND 0.43

**Comment by certuna** [comment]
Interesting. There's some trickery with service workers, in the sense that formally they require https, and localhost is http. So it could be that it's just an anomaly that only happens with the combination Windows+http+localhost, but let me do some more testing.

**Comment by Dnouv** [comment]
Actually, I also came across this information so, there was an option in settings in Firefox related to Enable Service worker over HTTP(as in the image below), I enabled it, but still no results, the service worker was not up and running.

image

**Comment by certuna** [comment]
yeah that's odd. If you connect to the same server over regular https (custom domain name + cert) does it still happen?

**Comment by Dnouv** [comment]
Sorry, @certuna, I am not sure if I completely understood your question, but the service worker was up and running on the demo site, and it was supposed to be detected on localhost as mentioned on this [site](https://web.dev/when-to-use-local-https/), but for some reason, it is not. I tried the solution mentioned [here](https://stackoverflow.com/questions/34160509/options-for-testing-service-workers-via-http), but it is still not showing up, here is a lighthouse report of localhost,



Thank you!

**Comment by deluan** [comment]
Superseded by #1358

**Pull request closed without merging**
