### PR TITLE
Top songs

### PR DESCRIPTION
**Pull request by Dnouv**
This PR introduces a Top Songs panel on the Artist Details page.
Here are the changes,

Panel closed,

Panel open,

Feedbacks are most welcomed. Thank you!

### CODE REVIEW

**Comment by Dnouv** [comment]
Now, also available on Mobile views, the change is that the Top Songs panel is not collapsable on mobile view.

top songs page on mobile view

Suggestions are most welcomed. Thank you!

**Comment by metalheim** [comment]
@Dnouv do we really need the tracknumber in this TopSong list (pre-pended to the tile in your screenshots)?

imho, the tracknumber is album context and doesn't really matter here. 
If anything, its a bit distracting.

**Comment by metalheim** [comment]
What happens if there is no top songs?
1. because last.fm is not activated
2. if last.fm is active, but the artists cant be found/no songs could be matched

**Comment by Dnouv** [comment]
Apologies for the late reply, @metalheim . If there are no "Top Songs" on the Desktop view, there will be no dropdown, and for the mobile view, the page will remain as it is now without the "Top Songs."
Regarding the "track number", the Album song list was fetched from `AlbumSongs` with a filter, so the "track number" was already there. I'll discuss with deluan and see if there are any other alternatives to fetch the song list.

Feel free to comment. Thank you!

**Comment by peperunas** [comment]
Looks great!

**Comment by BobWs** [comment]
Is this implemented already or is it still work in progress?

**Comment by Dnouv** [comment]
Hello peperunas and BobWs,
Thank you so much for the feedback, yes it's still in progress not yet merged. 
I'll try to finish it as soon as get some time.
Thank you!

**Comment by Dnouv** [comment]
Hello @deluan 
Sorry for the so... long delay. I have made the required changes now the tracknumber is gone from TopSongs. Please have a review.
Thank you!
image

**Comment by BobWs** [comment]
I guess this is still a work in progress?

**Comment by adamantike** [comment]
@Dnouv, do you have bandwidth to tidy up this PR? It would be great to see this merged!

**Comment by thecarlhall** [comment]
Could someone trigger the build again? I'd like to contribute whatever changes are needed to tidy this up. I found 1 js lint locally after rebasing on `master`.

**Comment by BobWs** [comment]
Still work in progress?

**Comment by tbleiker** [comment]
waiting for this as well :smile:

**Comment by deluan** [comment]
Thanks for this PR @Dnouv, but as we rewriting the UI, this PR is obsolete. Once the new UI is out we will start working on add these features to it, and you are welcome to work on that too.

Thanks for your efforts!

**Pull request closed without merging**
