### PR TITLE
Implementation of multiple genres

### PR DESCRIPTION
**Pull request by deluan**
This PRs imports all genres available in the files' tags. It also split genres. Ex: `Rock/AltRock` would become two separated genres: `Rock` and `AltRock`. Separators can be specified using `Scanner.GenreDelimiters` option, default is `;/,`

It also introduces "Genre" filters for Songs, Albums and Artists in the UI:
Screen Shot 2021-07-17 at 9 17 33 PM

Due to limitations in the Subsonic API, only the first genre is sent to the clients, but filtering by any of an album's genre works as expected.

Multi-valued `genre` tags can only be read using `Scanner.Extractor=taglib`. `ffmpeg` does not support it (but ND will split `genre` tags based on the `Scanner.GenreDelimiters` option, as explained above)

TODO:
- [x] Add M2M relation between genre and album/artist/media_file
- [x] Support filtering by genres
- [x] Add filters in the UI
- [x] #119
- [x] Display all songs genres in the UI

### CODE REVIEW

**Comment by certuna** [comment]
Something wrong with append/replace algorithm:
- genre "Pop", scan
- ND shows genre "Pop"
- change genre to "Rock", rescan
- ND shows genres "Pop", "Rock"

**Comment by certuna** [comment]
And I can confirm the issue noted by metalheim on Discord, for null-separated id3v2.4 genres `Pop<null>Rock` Navidrome will generate `Pop`, `Rock` and `Pop Rock`.

**Comment by certuna** [comment]
Another bug:
had an album with two tracks, tagged `Pop` in id3v2.4

- changed track 1 to `Pop<null>Rock<null>Reggae`
- changed track 2 to `Pop;Country;Bluegrass`
- rescan

Result: album shows in ND as `Pop`, `Country`, `Bluegrass`

**Comment by certuna** [comment]
It might also be useful to (on creation of a new record in the `genre` table) match the genre name against the MusicBrainz [genre list](https://musicbrainz.org/genres) and store `mbz_genre_id` as a column in the genre table

**Comment by deluan** [comment]
> Something wrong with the append/replace algorithm:
file has genre Pop, scan
ND shows genre Pop
change genre tag to Rock, rescan
ND shows genres Pop, Rock

This is fixed.

> And I can confirm the issue noted by metalheim on Discord, for null-separated id3v2.4 genres Pop<null>Rock Navidrome will generate Pop, Rock and Pop Rock. This also happens with Vorbis/FLAC (multiple GENRE frames).

Fixed as well

> Another bug:
album json returns Pop, Country, Bluegrass (i.e., something goes wrong when rolling up track genres to the album level)

Could not reproduce in my local. Maybe fixed as well? Can you try again with the latest build?

> It might also be useful to (on creation of a new record in the `genre` table) match the genre name against the MusicBrainz [genre list](https://musicbrainz.org/genres) and store `mbz_genre_id` as a column in the genre table. That prepares the work for inclusion of this id in a `/genre` API endpoint, and would enable things like clickable links to the MusicBrainz genre page, etc.

This can be a future improvement. I'd have to cache the MB's genre table locally, and refresh it from time to time. Maybe a separated GH issue?

**Comment by certuna** [comment]
Small thing: in the Songs view, when the Genre colum is included, only the first Genre is displayed, i.e. `Pop` when genres are `Pop` and `Rock`. Don't know if that's what we want, of if we want to have a concatenated string `Pop, Rock` instead.

**Comment by deluan** [comment]
@certuna The list could get long.... That's why I decided to keep only the "main" genre (the first one). But I'm open to add the complete list. Or maybe just show the first two and `...` to indicate there's more? Like `Pop, Rock, ...`

I'm merging this now, as the main functionality is in place, and we an improve it later.

**Pull request merged**
