### PR TITLE
Add Basque localisation

### PR DESCRIPTION
**Pull request by xabirequejo**
Initial Basque localisation

### CODE REVIEW

**Comment by deluan** [comment]
Thanks!

**Comment by deluan** [comment]
Tip: If you don't have a dev environment locally to test your changes, instead of pushign changes and waiting for it to build, you can create a folder in your Navidrome data folder like
`resources/i18n` and put your `eu.json` file there. So, if for example your Data Folder is `/data`, the complete path would be:
```
/data/resources/i18n/eu.json
```

After every change to the file, you need to restart Navidrome for it to pick up the latest version.

**Comment by xabirequejo** [comment]
Thanks, that's what I'm going to do to see the localisation live and improve the quality overall, but right now I'd like to fix the syntax (?) issue that it's making the tests fail.

I saw the extra dash in my first attempt, but now I don't know what I need to fix.

**Comment by deluan** [comment]
I added a better error handling for i18n files. Update your branch and it should show the error

**Comment by xabirequejo** [comment]
Well, I don't know how to get more information about the error.
All I see is

> • [FAILED] [0.016 seconds]
> Translations I18n files [It] contains only valid json language files
> /__w/navidrome/navidrome/server/nativeapi/translations_test.go:18
> 
>   [FAILED] i18n/eu.json
>   Expected
>       <*json.SyntaxError | 0xc0003e8438>: 
>       invalid character '"' after object key:value pair
>       {
>           msg: "invalid character '\"' after object key:value pair",
>           Offset: 2254,
>       }
>   to be nil
>   In [It] at: /__w/navidrome/navidrome/server/nativeapi/translations_test.go:30 @ 09/01/24 14:25:40.431

It makes me think the issue is the string #162 (`"addNewPlaylist": "Sortu \"%{name}\"",`), but I believe it's the same in English, so it must be something else?

**Comment by deluan** [comment]
With the new i18n lint job, you can check the output of the "Lint i18n files" job:

Screenshot 2024-09-01 at 11 33 45 AM

**Comment by deluan** [comment]
It is passing now \o/

Let me know when you think it is ready to merge

**Comment by xabirequejo** [comment]
It is ready to merge. I won't change anything else for now.

Thank you very much for your help.

**Pull request merged**
