### PR TITLE
Add support for Styling the player

### PR DESCRIPTION
**Pull request by Dnouv**
This PR introduces a method to style the player by adding some of the pre-defined properties in the `player{}` object in the theme file; they are as follows:
```
overrides:{...},

player: {
    theme: 'light',
    bgcolor: '',        //style background color of the player
    durcolor: '',       //style the duration and duration slider color
    btncolor: '',       //style the button colors
    hovbtncolor: '',    // style the button color in hover state  
  }
```
At the moment, only these few styles can be modified, but the other style modifications could be added as per future needs.

Feedbacks are most welcomed. Thank you!

### CODE REVIEW

**Comment by Dnouv** [comment]
@deluan, I do not know why but whenever I am creating a new branch from master and push it, all the old commits of the master branch also get pushed. I tried rebasing the branch, but still negative results. Sorry, this might be the second time, but could you please help me out with this also. Thank you!

**Comment by deluan** [comment]
Thanks for the PR, will take a look tomorrow. To avoid the issue with the branch, you must bring the latest from upstream (navidrome/navidrome), make sure your master is in sync with upstream, then create a branch out of it.

Let me know if you still have issues with that, so I can try to find a good tutorial about it. Maybe this can be helpful: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by Dnouv** [comment]
Thank you so much @deluan, the guide doc was too good and easy to understand. I truly appreciate it.

**Comment by deluan** [comment]
Hey it does the trick, but has an issue where if I switch the theme from one with custom colours to one that does not have them, it keeps the custom colours from the previous theme.

Also, it would be better to use the same names the player itself uses:
https://github.com/lijinke666/react-music-player#bulb-customize-theme

Not sure if you saw this comment from the player's author: https://github.com/lijinke666/react-music-player/issues/94#issuecomment-611385308

One more thing: It would be awesome if we could have a complete example in the dark and/or light theme, so theme authors could use it as reference.

**Comment by deluan** [comment]
Hey @Dnouv, I ended up doing some research and implemented the approach suggested by the player's author:  https://github.com/navidrome/navidrome/commit/a1551074bbabbf0a71c2201e1938a31e678e82cf 

Not a great option, but it works. I'll try to see if we can use LESS or SASS dynamically before merging to master.

**Comment by Dnouv** [comment]
> Not sure if you saw this comment from the player's author: [lijinke666/react-music-player#94 (comment)](https://github.com/lijinke666/react-music-player/issues/94#issuecomment-611385308)
>
I indeed went through this and all other issues which mentioned the word theme, and from these conversations, I got the idea to introduce the overriding classes. As for the example looks like you did already provided it in [here](https://github.com/navidrome/navidrome/blob/master/ui/src/themes/dark.css.js). Making use of LESS sounds nice, but when trying to implement the overrides as mentioned on the `jinke-player` site using LESS, it was not successful as mentioned [here](https://stackoverflow.com/questions/57749719/using-less-files-with-react) it does require some extra steps to run in React.

**Comment by deluan** [comment]
Hey @Dnouv, I'm closing this for now, as we have a solution in place. Maybe later if we can figure out how to add LESS to the project without ejecting it, we can revisit this. 

Thanks for the help!

**Pull request closed without merging**
