### PR TITLE
feat: Adds Audio Channel Metadata - #1036

### PR DESCRIPTION
**Pull request by mayanez**
First off awesome project! I'm looking to get familiar with the codebase to start adding a few missing features for classical music (https://github.com/navidrome/navidrome/issues/1036). I'm starting off small and figured this would be a good contribution although not in the linked issue since it is especially for those with multi-channel versions of the same track in their library.

I'm fairly new to Go as well so let me know if anything is off on that front.  With regards to the current changes two things I wasn't able to piece together:
* the naming convention for the `db/migration` file
* the configuration for prettier. It looks like `SongList.js` needs to run it.

If I missed anything regarding the contributing conventions let me know.

Cheers!

### CODE REVIEW

**Comment by deluan** [comment]
Hey, thanks for this!

> First off awesome project! I'm looking to get familiar with the codebase to start adding a few missing features for classical music (#1036). I'm starting off small and figured this would be a good contribution although not in the linked issue since it is especially for those with multi-channel versions of the same track in their library.

Is `channels` really that important? Can you send me an example of file with more than 2 channels?

> 
> I'm fairly new to Go as well so let me know if anything is off on that front. With regards to the current changes two things I wasn't able to piece together:
> 
> * the naming convention for the `db/migration` file

To create an empty migration skeleton, run `make migration`. Ex: `make migration name=add_mediafile_channels`

> * the configuration for prettier. It looks like `SongList.js` needs to run it.
> 

Yeah, it is breaking the build. Usually you install a prettier plugin in your IDE and enable autoformat with it. You can also run `npm run prettier` inside the `/ui` folder. To be sure you don't push broken code, setup your git hooks (`make setup-git`)

> If I missed anything regarding the contributing conventions let me know.

I'll review the PR as soon as I can

**Review by deluan — CHANGES_REQUESTED** [review]
Looks good, just missing the support for channels in the `ffmpeg` extractor. Can you please implement it?

**Comment by mayanez** [comment]
Thanks for the feedback. I'll try to address your comments as best I can and will circle around if I uncover any issues.

> Is `channels` really that important? Can you send me an example of file with more than 2 channels?
> Its more common for classical music and other live music recordings. The primary sources for this are SACD, Blu-ray, and DVD. 

You can find sample tracks here: https://oppodigital.com/hra/dsd-by-davidelias.aspx

**Comment by mayanez** [comment]
While going over the `ffmpeg` scanner I found that using `ffprobe`, which is part of the `ffmpeg`,  packages can significantly simplify parsing. I've chosen to make it output `json` so that it's easily parse-able and refactored the necessary parts. It should be more robust to any future ffmpeg version changes as well.

**Comment by deluan** [comment]
Thanks for taking a stab at the `ffmpeg` extractor. Unfortunately there's one important thing you overlooked: batching. 

Originally I tried to use `ffprobe` for extracting metadata (you may find references to it in [GitHub history](https://github.com/navidrome/navidrome/blob/8a1110044c08cff1503247cb1e99b412fd8be6cf/scanner/metadata.go)), for the same reasons you pointed above, but it was too slow as it has to exec one `ffprobe` command for each track file. For a few hundred songs it will be slow, but may not have a huge impact. But for libraries over 50K songs (we have users with >1Mi songs), this is simply unacceptable.

The way I found to speed up this was to call `ffmpeg` passing all files in a directory in one command only, drastically reducing the time required to import all songs. Unfortunately `ffprobe` does not support multiple input files, nor `ffmpeg` outputs json or other more parseable formats...

Anyway, I'm afraid I won't be able to accept this change. If you are having trouble parsing `ffmpeg`'s output with regex, please reach ou to me through Discord and I can help with that.

**Comment by deluan** [comment]
Hey, sorry for the delay. I already reviewed it and looks good. Will try it this weekend and if everything is fine, will merge this

**Review by deluan — APPROVED** [review]
LGTM. Thanks for the contribution!

**Review by deluan — CHANGES_REQUESTED** [review]
Actually I just tried the `ffmpeg` extractor, and it is not able to get channels from some files (M4A and OGG). Here are some samples:

[01-01 The Hollow.ogg.zip](https://github.com/navidrome/navidrome/files/7113180/01-01.The.Hollow.ogg.zip)
[02 I Get Around.m4a.zip](https://github.com/navidrome/navidrome/files/7113185/02.I.Get.Around.m4a.zip)

**Comment by mayanez** [comment]
> Actually I just tried the `ffmpeg` extractor, and it is not able to get channels from some files (M4A and OGG). Here are some samples:
> 
> [01-01 The Hollow.ogg.zip](https://github.com/navidrome/navidrome/files/7113180/01-01.The.Hollow.ogg.zip)
> [02 I Get Around.m4a.zip](https://github.com/navidrome/navidrome/files/7113185/02.I.Get.Around.m4a.zip)

Looks like it's possible to have a language in the stream. I've updated the regex to account for it and added appropriate test cases.

**Pull request merged**
