### PR TITLE
Add support for local album artist images

### PR DESCRIPTION
**Pull request by kgarner7**
This PR seeks to add support for adding and displaying artist images from local files.
Changes:
- New Configuration options:
  - `ArtistArtPriority`: similar to cover art, determine how to find images. For now, this is just `artist.*`
  - `BaseDomain`: Personally a terrible name, but it's the external URL that Navidrome is accessed by (please give better name)
  - `BaseDomain` is required to show local artist images
- Scan for artist images: 
  - When scanning an album, look for artist images and store that along with the album.
  - For artists, get all of the albums and pick one of the non-empty paths (`MAX` seems to accomplish this goal)
  - This requires a few extra columns: `artist_image_path` for albums, and `image_path` and `image_id` (potentially redundant) for artists
- Modifications to subsonic to select between external or local
  - When getting art, return URLs for the images by using the `getCoverArt` endpoint (authenticated).
  - The core of this is `getBaseArtistImageUrl` + `ArtistImageUrl`. This does require passing around `baseUrl` (better name pending) around
  
Not sure what the standard sizes are for images. I just selected 156, 300, and full size?
As an aside, it would be nice to change BaseURL -> BasePath, but that's a breaking change.

### CODE REVIEW

**Comment by krokenn** [comment]
please include local .nfo files aswell.

**Comment by ghenry22** [comment]
This assumes a specific file structure to find the local artist image / artist info where all albums are under an artist folder.  Would have to add documentation about the required file system layout.  Until now navidrome hasn't really cared about file system layout but it gets harder when you start looking outside the immediate album for contextual info.

**Comment by kgarner7** [comment]
> please include local .nfo files aswell.

I personally don't have any experience with .nfos, if you could give an example (even for a dummy file), though, I could see what I can do.

**Comment by kgarner7** [comment]
> This assumes a specific file structure to find the local artist image / artist info where all albums are under an artist folder. Would have to add documentation about the required file system layout. Until now navidrome hasn't really cared about file system layout but it gets harder when you start looking outside the immediate album for contextual info.

Kinda? I used the pattern Navidrome uses for finding album cover art (using the directory's `cover.*` or similar) to find the **album artist**. I do require all files in a given album (/directory) be by the same album artist for this feature to work, but not the artist / album / track structure proposed. Of course, this won't pick up individual artists (but that definitely requires some additional requirements). If for some reason you have multiple `artist.jpg` for the same artist (e.g., you have multiple albums by the artist, in any location in your library), it would pick one randomly.

If you have a recommendation for something that requires less layout requirements than proposed, I'd be happy to hear it. 

I would be fine adding some documentation to the settings (if this eventually gets through) noting that for this feature to be most effective, you would need all songs in a directory to be the same album artist.

**Comment by ghenry22** [comment]
> > This assumes a specific file structure to find the local artist image / artist info where all albums are under an artist folder. Would have to add documentation about the required file system layout. Until now navidrome hasn't really cared about file system layout but it gets harder when you start looking outside the immediate album for contextual info.
> 
> Kinda? I used the pattern Navidrome uses for finding album cover art (using the directory's `cover.*` or similar) to find the **album artist**. I do require all files in a given album (/directory) be by the same album artist for this feature to work, but not the artist / album / track structure proposed. Of course, this won't pick up individual artists (but that definitely requires some additional requirements). If for some reason you have multiple `artist.jpg` for the same artist (e.g., you have multiple albums by the artist, in any location in your library), it would pick one randomly.
> 
> If you have a recommendation for something that requires less layout requirements than proposed, I'd be happy to hear it.
> 
> I would be fine adding some documentation to the settings (if this eventually gets through) noting that for this feature to be most effective, you would need all songs in a directory to be the same album artist.

Ah ok I didn’t realise you were putting the artist image in each album folder.  You’re right that doesn’t create any new requirement for directory structure done that way.

if you assumed an artist / album / tracks structure then you could have a single album artist image in the artist folder that can be applied to for any album, this would be more efficient but does have the specific folder structure assumption.

I’m not sure how no files are passed as they are completely arbitrary formats, I’d have a look at how kodi formats and parses them as that would likely be the format everyone uses.  Lidarr optionally creates these for you when it manages your music as well.

**Comment by ghenry22** [comment]
[nfosample.zip](https://github.com/navidrome/navidrome/files/10035629/nfosample.zip)

Here is an example of an artist.nfo and an album.nfo as used by kodi for local metadata.

album.nfo goes into the album folder
artist.nfo goes into the artist folder

assuming artist/album/tracks arrangement.  You could obviously duplicate all artist info into each album but having it all stored in 1 location as a single point of truth or point to edit would make more sense to me even if it does impose a limitation on the directory structure.

**Comment by c0utta** [comment]
My unique requirement is to display the artist image when playing a compilation, since most compilation art is boring (except maybe for soundtracks).

If that is not possible, the original Subsonic had an image path stored in the media_file table.  This enabled those with SQL skills (about the only skill I have) to manipulate the image path.  Would that require a large amount of code refactoring?

**Comment by deluan** [comment]
@kgarner7 As we discussed, I'll close this now, as I reimplemented the CoverArt logic and ended up with a more integrated approach. Thanks for this anyway.

@c0utta, the way to handle this would be to embed the artwork in the audio file, then Navidrome would use it when playing a song. Not sure about the other Subsonic clients.

**Comment by deluan** [comment]
@ghenry22 , I may add support for these sidecar files in the future.

**Pull request closed without merging**
