### PR TITLE
Enhanced Mobile Login Screen

### PR DESCRIPTION
**Pull request by Dnouv**
As mentioned in issue #927, the log-in screen was required to be enhanced. I have tried to enhance the login screen for mobile devices.
Here are the screenshots after and before the change:
On demo page:
navid_demo-login

After changes:
navid-login

Please feel free to provide feedback. Thank you!

### CODE REVIEW

**Comment by samarsault** [comment]
Looks goood ! Nice @Dnouv 

I feel it is better to have these changes in `Login.js`, and not the theme file(s) as it is improving the basic "starter" page for other themes.

Also, why limit this to mobile? This configuration would make the desktop version look better as well.

**Comment by Dnouv** [comment]
> Also, why limit this to mobile? This configuration would make the desktop version look better as well.
 
Thanks, @samarsault. About desktop support, I was unsure whether it would look good on the desktop, so I thought first of implementing it for mobile, and as per feedback from @jvoisin or @deluan will try adding it for desktop.
You were working on Spotify theme, so I decided to not interfere in the `Login.js`, as it would have affected your themes login design.

**Comment by jvoisin** [comment]
I don't know much about javascript, let alone react, but it looks really cool!

**Comment by Dnouv** [comment]
Thanks, @jvoisin, for your feedback. Should I head towards implementing it for the desktop screen?

**Comment by jvoisin** [comment]
Sure :)

**Comment by deluan** [comment]
I like the design, but I have a couple of concerns:
- It removed the "Welcome" message. Was it intentional?
- It makes the button visually different from other buttons in the theme:
Screen Shot 2021-04-01 at 9 48 18 AM

**Comment by Dnouv** [comment]
@deluan, thanks for your feedback. I did not make any changes to the welcome message; where could I find this welcome message? 
About the button, I thought making it a little rounded and adding a shadow might look better. Should I reset it to the previous style? (Only the sign-in button is changed)

**Comment by deluan** [comment]
The message can be set with the `UIWelcomeMessage` config option. The current value in the Demo instance is:
```
UIWelcomeMessage = "Please login with username &nbsp; <strong>demo</strong> &nbsp; and password &nbsp; <strong>demo</strong>"
```

I liked the new style, what I'm saying is that the button's shape and color would become different from the rest of the app. Maybe we can reset it back to the previous style and experiment with a new "Light" theme? 

Also, I see changes in the "Dark" theme. What changed? Can you post screenshots?

**Comment by Dnouv** [comment]
@deluan, sure experimenting with a new light theme would be nice. For now, I would reset the button style and color to the previous style, please let me know whether or not should I reset the dark theme's button.
Sorry, I forgot to add the dark theme screenshots; here are they
On branch master:
navid-master-login-dark

After the edit:
navid-login-deskdark

There was no welcome message on the master, so maybe that is why the welcome message was not thereafter the edit.

Feedbacks are most welcomed. Thank you!

**Comment by Dnouv** [comment]
@deluan, I have reset the button color and style; here are the screenshots after the changes,
navid-login-reset

Please feel free to provide feedback, and please let me know should I create a PR for the new Light theme. Thank you!

**Comment by Dnouv** [comment]
@deluan, I have made the required changes for button style; it would be nice if you could review this once more. Thank you!

**Comment by Dnouv** [comment]
@jvoisin, it seems @deluan is quite busy, so could you please review this PR, as it is related to the login page design.

**Review by jvoisin — APPROVED** [review]

**Comment by Dnouv** [comment]
Thanks for your review, @jvoisin.

**Comment by deluan** [comment]
Looks good, but can we make the logo/icon larger in the component, instead of in the themes? Or else this won't be picked-up by the other themes.

**Comment by Dnouv** [comment]
Thanks for your feedback @deluan, actually, I thought it might interfere with the theme creators' design for their specific theme, but if it is ok, should I go ahead and make the changes for all themes in `Login.js`,

**Comment by deluan** [comment]
> I thought it might interfere with the theme creators' design for their specific theme,

As long as there's a way for the theme to override the icon properties (size, color, etc...) it is fine. We only have a handful of themes ATM, and only the Spotify-ish customized the login dialog. 

@samarsault, are you ok with the change of the login's logo size in the Spotiffy-ish theme?

**Comment by samarsault** [comment]
> As long as there's a way for the theme to override the icon properties (size, color, etc...) it is fine. We only have a handful of themes ATM, and only the Spotify-ish customized the login dialog.
> 
> @samarsault, are you ok with the change of the login's logo size in the Spotiffy-ish theme?

Yeah, since this improves the basic template from which other themes are built up, I think we are better off doing this customization in the component.

**Comment by Dnouv** [comment]
@deluan, I have made the changes in the component, and @samarsault, I have kept the logo size for Spotify-ish similar to the previous one.
Here are the screenshots, for themes after changes,
Spotify-ish:
nd-spotify

Light:
nd-light

Dark:
nd-dark

Please feel free to provide feedback. Thank you!

**Comment by samarsault** [comment]
Nice, can we keep the login form width in spotify-ish same as the other themes?

**Comment by Dnouv** [comment]
Sorry, @samarsault, I am unsure if I completely understood your question, but I have not made any changes to the login form width.

**Review by deluan — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
