### PR TITLE
feat: Add listenbrainz base url configuration

### PR DESCRIPTION
**Pull request by andyklimczak**
- ListenBrainz.BaseURL config value

### CODE REVIEW

**Comment by andyklimczak** [comment]
Fixes #1600

**Comment by iluvatyr** [comment]
any timeframe when we cant expect this? Just asking.

**Comment by andyklimczak** [comment]
Not sure why I get linter failures on files I don't think I affected. Would appreciate any insight:
```shell
Run git status --porcelain
  git status --porcelain
  if [ -n "$(git status --porcelain)" ]; then
    exit 1
  fi
  shell: /usr/bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.19.0/x64
 M scanner/tag_scanner.go
 M utils/cache/spread_fs.go
Error: Process completed with exit code 1.
```

**Comment by deluan** [comment]
Hey sorry for the long delay! Can you please rebase this PR? I'm planning to release a new version this week and would like to include this. Thanks!

**Comment by deluan** [comment]
> Not sure why I get linter failures on files I don't think I affected. Would appreciate any insight:
> 
> ```shell
> Run git status --porcelain
>   git status --porcelain
>   if [ -n "$(git status --porcelain)" ]; then
>     exit 1
>   fi
>   shell: /usr/bin/bash -e {0}
>   env:
>     GOROOT: /opt/hostedtoolcache/go/1.19.0/x64
>  M scanner/tag_scanner.go
>  M utils/cache/spread_fs.go
> Error: Process completed with exit code 1.
> ```

This was caused by the upgrade to Go 1.18, changes to the `gofmt` output. It is not related to your changes. It is already fixed in master, please rebase your changes and it should work fine. Thanks!

**Comment by andyklimczak** [comment]
Sweet, it should be rebased and happy. Let me know if something is off
Also pushed up a PR in the documentation repo https://github.com/navidrome/website/pull/89

Appreciate all your work :rocket:

**Review by deluan — APPROVED** [review]
I just pushed a couple of small changes, the main one being to use url.JoinPath to concatenate paths, as the URL is now externally configurable. This handles the cases where the user forgets to end the URL with `/`, and also remove relative paths.

Looks good otherwise. Thanks!

**Comment by deluan** [comment]
Ops, `url.JoinPath` is not available in GoLang 1.18. Will fix this and merge tonight or tomorrow morning.

**Pull request merged**
