### PR TITLE
Fix Ligera Error

### PR DESCRIPTION
**Pull request by Dnouv**
Fixes [error](https://github.com/navidrome/navidrome/pull/1083#issuecomment-839320614).

### CODE REVIEW

**Comment by deluan** [comment]
Did you run `npm run prettier` after updating the dependencies?

**Comment by Dnouv** [comment]
Yeah, I did the same.

**Comment by deluan** [comment]
> Yeah, I did the same.
> "prettier": "2.3.0"

Ok, close you editor, the run:

```
make setup
cd ui
npm run prettier
```

After this, does it change the `ligera.js` file? It should, then you have to commit the changes.

**Comment by Dnouv** [comment]
Thank you so much @deluan. It worked.

**Comment by deluan** [comment]
> Thank you so much @deluan. It worked.

Great! After running `make setup` it should've configured a git hook that will only allow you to push if all tests, lint and prettier pass

**Comment by Dnouv** [comment]
Oh, but it was already running the 10 test suites and prettier also, after running `make setup`, it updated some of the go packages, was the issue related to the go package? Thanks!

**Comment by deluan** [comment]
No, the change that was making your PR fail was the upgrade to Prettier 2.3, for sure. Don't know why your environment was not picking it up.

**Comment by Dnouv** [comment]
This might be possible. Now I understood the error cause; thanks for helping me out.

**Pull request merged**
