### PR TITLE
build(ui): migrate from CRA/Jest to Vite/Vitest

### PR DESCRIPTION
**Pull request by deluan**
I was hoping to avoid doing this before the new UI, but everytime I have to build the UI with CRA, or start `make dev`, i die a little.

### CODE REVIEW

**Comment by deluan** [comment]
@certuna with this change, I replaced our custom `serviceWorker` with a Vite plugin. Whenever you have the chance, can you please verify if this behaves well in your setup.

**Comment by kgarner7** [comment]
The PWA appears to work, but the name is a bit different. With previous Navidrome on iOS, I have a blue icon with N. With the new one, it's black and U. Otherwise, it seems to work fine (in neither case do I see an icon for PWA)

**Comment by deluan** [comment]
> The PWA appears to work, but the name is a bit different. With previous Navidrome on iOS, I have a blue icon with N. With the new one, it's black and U. Otherwise, it seems to work fine (in neither case do I see an icon for PWA)

Thanks for the feedback. Yeah, I need to configure the PWA manifest. Will try to do it tomorrow.

**Comment by kgarner7** [comment]
Is the manifest supposed to look like
```json
{"0":".","1":"/","2":"p","3":"u","4":"b","5":"l","6":"i","7":"c","8":"/","9":"m","10":"a","11":"n","12":"i","13":"f","14":"e","15":"s","16":"t","17":".","18":"w","19":"e","20":"b","21":"m","22":"a","23":"n","24":"i","25":"f","26":"e","27":"s","28":"t","name":"ui","short_name":"ui","start_url":"./","display":"standalone","background_color":"#ffffff","lang":"en","scope":"./"}
```
?

**Comment by deluan** [comment]
> Is the manifest supposed to look like
> 
> ```json
> {"0":".","1":"/","2":"p","3":"u","4":"b","5":"l","6":"i","7":"c","8":"/","9":"m","10":"a","11":"n","12":"i","13":"f","14":"e","15":"s","16":"t","17":".","18":"w","19":"e","20":"b","21":"m","22":"a","23":"n","24":"i","25":"f","26":"e","27":"s","28":"t","name":"ui","short_name":"ui","start_url":"./","display":"standalone","background_color":"#ffffff","lang":"en","scope":"./"}
> ```
> 
> ?

Where are you getting this from?

**Comment by kgarner7** [comment]
/app/manifest.webmanifest (the manifest that Navidrome uses)

**Pull request merged**
