### PR TITLE
chore(beep): Use maintained fork of beep

### PR DESCRIPTION
**Pull request by dmarcoux**
faiface/beep isn't maintained anymore.

There is this notice at the top of the README:

> This repo is not under active development anymore and has been archived. Continued development has been migrated to [gopxl/Beep](https://github.com/gopxl/beep). A big thank you to [faiface](https://github.com/faiface) for creating this awesome library and for all the hard work put into it. We encourage old and new users to check out the new repo and contribute to it.

### CODE REVIEW

**Comment by dmarcoux** [comment]
The next step would be to update this dependency to its latest version. For now, I sticked to the same version to prevent issues.

**Comment by deluan** [comment]
Thanks for this. We are not actually using `beep` anymore, so maybe a better action here would be to remove it completely? @ms140569 any thoughts?

**Comment by dmarcoux** [comment]
Oh, in this case I could remove everything under [core/playback/beepaudio](https://github.com/navidrome/navidrome/tree/master/core/playback/beepaudio), right? I can do this in another PR.

**Comment by deluan** [comment]
@dmarcoux Let's wait for an opinion from @ms140569. Maybe he is off for the holidays, I don't know.

**Comment by ms140569** [comment]
Hi *, sorry for the delay. I was down with a cold for some time. I think we could drop all references to beep, since we don't use it anymore. 

@dmarcoux - thanks for finding this out. We'll keep this in mind if we need beep in the future!

**Comment by dmarcoux** [comment]
Alright, thank you @ms140569 for the reply. I will close this PR and open another one to instead remove beep.

**Pull request closed without merging**
