### PR TITLE
New light Theme

### PR DESCRIPTION
**Pull request by Dnouv**
This PR is an enhancement to the current Light theme.

### CODE REVIEW

**Comment by Dnouv** [comment]
Sorry, I was about to add to screenshots, but at the last moment, I decided to do a color change.
Here are the screenshots after the changes

On login page:
image


On AlbumGrid page:
image

On AlbumList view page:
image

On AlbumDetails page:
image

Feedbacks are most welcomed. Thank you!

**Comment by jvoisin** [comment]
To be honest, I'm not a huge fan of those colours, especially the flashy-flashy blue.
Also, maybe create an other them, instead of replacing the current default one?

**Comment by Dnouv** [comment]
Thanks for your review @jvoisin, so @jvoisin, should I create a new theme, sort of blue theme, or replace the blue color?

**Comment by jvoisin** [comment]
Both I think :)

**Comment by Dnouv** [comment]
@jvoisin, how about this color? It is almost the same as the Navidrome logo color; also, I have removed the blue gradient from the page.
image

Feedbacks are most welcomed. Thank you!

**Comment by shishir610** [comment]
At first glance, I would suggest -
1. Removing background colour from selected "All Albums" (maybe have it on hover only) 
2. Adding a subtle drop shadow for the album cover
3. Making grid selection icon white OR background lighter blue.

**Comment by Dnouv** [comment]
Thanks for your feedback, @shishir610; I would for sure replace the Album grid background color regarding the "All Albums," there was an issue opened regarding highlighting the currently selected state, so I thought adding a background change, would be better. Well, there is a blue shadow around the album cover; maybe it's not clearly visible in the screenshot.

**Comment by shishir610** [comment]
I see, you can make -
1. Background color for highlighting the currently selected state subtler. 
2. Use a black shade for drop-shadow

**Comment by Dnouv** [comment]
@jvoisin, @shishir610, below is the screenshot of the new theme, please have a look:
image
 
AlbumDetails Page:
image


Please feel free to provide feedback. Thank you!

**Comment by Dnouv** [comment]
@deluan, it would be nice if you could review this theme.

**Comment by deluan** [comment]
Code-wise looks good. In terms of appearance, I'm ok with it, not huge fan of light themes and I'm color blind 😛 
I'll take it for a spin later to see if there is any undesired effect in the UI.

Also, I prefer that you name it something else and leave the "Light" theme as it is

**Comment by deluan** [comment]
@Dnouv did you push your latest changes? This is what I get from this branch:
Screen Shot 2021-04-07 at 2 58 52 PM

**Comment by Dnouv** [comment]
Thanks for your feedback, and sorry, I was not aware of this; I would create a new theme name for it in the next commit.
Ah, my bad, I have not pushed the latest changes.
Just a minute, I would push them now.

**Comment by deluan** [comment]
@Dnouv AddToPlaylistDialog select is really hard to read/use:
Screen Shot 2021-04-07 at 3 29 40 PM

**Comment by Dnouv** [comment]
Thanks for your review @deluan, here it is fixed now,
image
 
Please feel free to provide feedback. Thank you!

**Comment by deluan** [comment]
Looks good now. Just missing the rename. Feel free to not make the name too serious :)

**Comment by Dnouv** [comment]
@deluan, I have renamed the theme; well, I tried my best to keep the name simple

**Review by deluan — APPROVED** [review]
LGTM

**Pull request merged**
