### PR TITLE
Add whole playlist when a specific song is played from it.

### LINKED ISSUE #703: Starting a playlist from a specific song only adds the remainder of the playlist to the queue (Web UI)
The expected behaviour was that when I start playing a playlist from a specific song, the whole playlist is added to the queue and the specific song starts playing. That way, I can still go the previous song in the playlist since it is all in the queue. 

However, in the Web UI, only the songs after the specific song are added to the queue. 
This is not the case in Music Stash nor DSub.

### PR DESCRIPTION
**Pull request by YashJipkate**
This PR makes the UI add the whole playlist when a specific song is played from it, while the specific song plays.

Fixes #703.

### CODE REVIEW

**Comment by deluan** [comment]
This is awesome! But unfortunately it makes the issue https://github.com/navidrome/navidrome/issues/650 even worse: It always go to the first song in the queue when I click on "Play Next"....

I think we need to understand #650 first, or maybe even rewrite the redux integration with the player, so we can start adding other desired behaviours like this one.

**Comment by YashJipkate** [comment]
But isn't this issue (the moving of current playing to the first one) is already present in `master`? Or is there some additional regression that is caused by this PR?

This is from `master`-

https://user-images.githubusercontent.com/34203227/113546891-87603280-960a-11eb-920c-a6df5aedc136.mp4

**Comment by Rishabh-malhotraa** [comment]
> This is awesome! But unfortunately it makes the issue #650 even worse: It always go to the first song in the queue when I click on "Play Next"....
> 
> I think we need to understand #650 first, or maybe even rewrite the redux integration with the player, so we can start adding other desired behaviours like this one.

How about we append the remaining songs to the end of the queue, this way we fix the play next issue

6th song is pressed in a playlist of 10 songs
so we can make the queue to look something like this
`6-7-8-9-10-1-2-3-4-5`

**Comment by deluan** [comment]
> 6th song is pressed in a playlist of 10 songs
> so we can make the queue to look something like this
> `6-7-8-9-10-1-2-3-4-5`

That's not an expected behaviour. No player out there does this.... (remember [Jakob's Law](https://uxplanet.org/the-10-best-ux-laws-and-principles-7980ff22e424#9351))

**Pull request closed without merging**
