### PR TITLE
Implement Sharing

### LINKED ISSUE #748: Ability to share a subset of the library
It would be nice to be able to share an arbitrary subset (tracks, artists, albums, …) of my library with anonymous users.

### PR DESCRIPTION
**Pull request by deluan**
This is an initial implementation of Sharing:
> One of the nice features of Subsonic is its [ability to generate a sharing link](http://www.subsonic.org/pages/features.jsp) for a track/album/artist/playlist to send to friends, so that they can listen/download the music without having an account on your instance. This is a nice alternative to Youtube links to share music.

As there are still some rough edges, this feature will be disabled by default in 0.49.0. To enable it you'll need to set `DevEnableShare=true` in your configuration.

Notes:
- If enabled, all users will have access to all current shares, including changing description and expiration, and will be able to create new ones. Currently there's no way to set permissions per user
- All generated sharable links will have the format: `http://yourserver.com/share/XXXXXXXXXX`, so if you have Navidrome behind a reverse proxy, be sure to allow traffic to `/share` 

Closes #748 

- [x] Add ways to create and manage shares in the UI
   - [X] Albums
   - [x] Songs
   - [X] Playlists
   - [x] Artists
- [x] Implement the Subsonic API related endpoints: 
   - [X] getShares
   - [X] createShare
   - [x] updateShare
   - [x] deleteShare
- [X] Add a standalone player (based on our current React Player)
- [x] Add meta-tags to html (to show some info about the shared music in chat platforms)

### CODE REVIEW

**Comment by jan666** [comment]
The share button is visible and you can create shares when `DevEnableShare=true` is not set. There is no "Shares" in the Menu and the created shares do not work - but the button is there and the shares are generated. I guess this is a bug?

**Comment by deluan** [comment]
> 

Yes it is! Fixed now, thanks for reporting.

**Comment by morbificagent** [comment]
Hi there,

wanted to try it, updated to the last git-version and added the DevEnableShare option in the toml...
But even after a restart no "share button" appears...:

image

**Comment by jan666** [comment]
@morbificagent it's `EnableSharing=true`

**Comment by morbificagent** [comment]
Great, its working with this!
Many thanks

**Comment by centralscrutinizer21** [comment]
Great work on this feature!
I was wondering what would be the best way to embed the shared link into a static web page (markdown,html, etc.) ?

**Pull request merged**
