### PR TITLE
feat(UI) : Extract urls from comments and link them to their correspoding sites - #1053

### PR DESCRIPTION
**Pull request by MoulinaPradhan**
Closes- #1053

Used an npm package [react-anchorme](https://github.com/potty/react-anchorme), which links the comment URLs to their corresponding site.

`BREAKING CHANGE`

The changes are made in the **AlbumDetails** file in the UI folder. There are changes in the **package.json**  file due to the installation of the package [react-anchorme](https://github.com/potty/react-anchorme).

https://user-images.githubusercontent.com/64212940/121768451-e185f280-cb7b-11eb-83ff-977a04e28ca1.mp4

### CODE REVIEW

**Comment by deluan** [comment]
Hey @MoulinaPradhan, thanks for taking a stab at this!

I took a quick look and I see a couple of issues:
1) You forgot to push the changes to the `package.json` file
2) The links should have a "link" color.

But most important: I don't think it is worth to add a new dependency just for this. It would make more sense to create a simple component which could be used in a similar fashion as `<Anchorme/>`, and this component would basically uses the regex suggested by @metalheim [here](https://github.com/navidrome/navidrome/issues/1053#issuecomment-827554143), and replace matches with a `<Link>` component, that already handles the styling for us.

What do you think?

**Comment by MoulinaPradhan** [comment]
I am thinking about a function like this 

```
const commentLink=(text) =>{
  const urlRegx = /(https?:\/\/)?[\w\-~]+(\.[\w\-~]+)+(\/[\w\-~@:%]*)*(#[\w\-]*)?(\?[^\s]*)?/gi
  const res = text.match(urlRegx)
  return res[0];
  }

```
which will be called in the `Link` tag like

`<Link to={commentLink(record.comment)}>{record.comment}</Link>`

What is your opinion?

**Comment by deluan** [comment]
Hey @MoulinaPradhan, sorry for not giving feedback on this before. The main issue with your implementation is that the comment can contain a mix of text and URL(s). Ex:
```
We are the best band in town!
Our website: https://theband.com
Buy our music: https://bandcamp.com/theband
```

In your implementation, you are considering that the comment only contains one URL and nothing more. That would not work with the example above.

**Comment by deluan** [comment]
I've finished this up in https://github.com/navidrome/navidrome/commit/c530ccf13854e3a840ddf63eef5e2323fbe2827d. Thanks for your effort!

**Pull request closed without merging**
