### PR TITLE
I919: Fix Navbar overlapping

### LINKED ISSUE #919: navbar overlapping scrollbar
### Description

Navbar and music bar overlaps scrollbar when profile dropdown is opened

### Steps to reproduce

1. Play any song
2. Click on your profile icon to open a dropdown
3. Notice the navbar and music bar overlaps scrollbar

### Platform information

 - Navidrome version: 0.41.0 (ba922bbf)
 - Browser and version: Chrome Version 89.0.4389.90
 - Operating System: Windows 10

### Screenshot
image

### PR DESCRIPTION
**Pull request by Dnouv**
As mentioned in issue #919, the navbar and the player were overlapping the scrollbar; when the user icon was clicked, I tried to resolve this issue by modifying some of the CSS properties of the body; this PR is an alternate solution without the use of `!important`. (Fixes #919 )

Here are the screenshots after the changes,
navid919n1

Feedbacks are most welcomed. Thank you!

### CODE REVIEW

**Comment by Dnouv** [comment]
@deluan, should I go ahead with this solution or the `react-admin` solution of disabling the scroll lock.

**Comment by deluan** [comment]
If you are talking about this: https://github.com/marmelab/react-admin/pull/6113, I'll upgrade our version of React-Admin in the next 2-3 weeks, so it is better to wait. We should always prefer a functionality/behaviour provided by RA instead of duplicating it on our side

I'm closing this, but if you are talking about something else, feel free to reach out.

**Comment by Dnouv** [comment]
The fix that `react-admin` used was `disbleScrollLock`, but it gets a different issue using this approach; please refer to the screenshot attached
image
(Since the scrolling is not locked, the popover menu remains on the screen when scrolling down)
@deluan, what are your thoughts on this issue?
Thank you!

**Comment by Dnouv** [comment]
@deluan, I understand you may be busy, but could you please provide your feedback on this issue.

**Pull request closed without merging**
