### PR TITLE
Added song/file quality info

### PR DESCRIPTION
**Pull request by Himanshunitrr**
Tried to implement this issue https://github.com/navidrome/navidrome/issues/726

### CODE REVIEW

**Comment by Himanshunitrr** [comment]
If some improvement is required in UI then please tell.

**Comment by jvoisin** [comment]
Can you please show screenshots?

**Comment by Himanshunitrr** [comment]
ss1
ss2
ss3
ss4

**Comment by Himanshunitrr** [comment]
@jvoisin added screenshots sir

**Comment by Himanshunitrr** [comment]
If something needs to be changed than please comment so that I can improve UI.

**Comment by Rishabh-malhotraa** [comment]
resolves #726

**Comment by Himanshunitrr** [comment]
created a new PR https://github.com/navidrome/navidrome/pull/918

**Pull request closed without merging**
