### PR TITLE
fix(SongTitleField.js): Fixed jumping of Title column in song lists due to play icon

### PR DESCRIPTION
**Pull request by Balaguru4580**
This fixes the issue #998. The title column now does not jump in case of difference in song title lengths.

Play icon now doesn't displace the title whenever it is loaded, maintaining vertical alignment of the song titles. Scale of play icon slightly increased for visibility.

### CODE REVIEW

**Comment by deluan** [comment]
Any screenshots? Video would be better :)

**Comment by Balaguru4580** [comment]
Of course. Screenshots are there in the issue thread. However, here's a video that shows it better.

Here's the problem.

https://user-images.githubusercontent.com/61746056/114304185-7d996c00-9aef-11eb-9187-a224a23051e3.mp4

Here's the solution I'm proposing.

https://user-images.githubusercontent.com/61746056/114304181-796d4e80-9aef-11eb-84cb-225a033a5bfd.mp4

**Comment by deluan** [comment]
I see that you made the space for the "playing" icon fixed, but now the `title` header is not aligned with the values... IMHO, this is worse than before.... Do you see any other solution? Ideally we would replace the number of the track with the playing icon, (similar to Spotify) but this may be too big of an effort. Thoughts?

Screen Shot 2021-04-15 at 8 12 23 PM

**Comment by Balaguru4580** [comment]
Ah, that was an oversight on my part.

I like the way Spotify handles it, but the problem is that there is too much space between the index and the title in album view, and the index is in a different location altogether in the songs view. 

Maybe there's a way to only alter the column width shifting without affecting the existing spacing arrangement of the play icons. I'll experiment with some more approaches and see what I can come up with.

**Comment by aniketbiswas21** [comment]
> the index is in a different location altogether in the songs view.

What are you implying by this? I actually worked on a pr(#819) that replaced the index with the playing icon. 

Maybe this is what you are looking for 

https://github.com/navidrome/navidrome/pull/819/files#diff-70a7f4baba7a986b74282bbf9b4b77a12bfb8de76fcb37f2579d2c177b481687R204-R209

**Comment by aniketbiswas21** [comment]
@Balaguru4580 Let me know if you need any help with this

**Comment by Balaguru4580** [comment]
@aniketbiswas21 What I meant is shown here. 

In the album view, the index (#) is right next to the Title. 

Screenshot_2021-04-16 Navidrome

However, in the all songs view, the index is much further away, so replacing that with the play icon might be a bit inconsistent.

Screenshot_2021-04-16 Navidrome(1)

I am trying some alternative approaches, the most destructive being just making the playing track bold and in theme colour. But I'm sure there's a way to keep the play icon as well. Since it's not currently a serious issue, I'll try out some more approaches.

Also thanks! I'll let you know if I need any help on this!

**Comment by aniketbiswas21** [comment]
> @aniketbiswas21 What I meant is shown here.
> 
> In the album view, the index (#) is right next to the Title.
> 
> Screenshot_2021-04-16 Navidrome
> 
> However, in the all songs view, the index is much further away, so replacing that with the play icon might be a bit inconsistent.
> 
> Screenshot_2021-04-16 Navidrome(1)
> 
> I am trying some alternative approaches, the most destructive being just making the playing track bold and in theme colour. But I'm sure there's a way to keep the play icon as well. Since it's not currently a serious issue, I'll try out some more approaches.
> 
> Also thanks! I'll let you know if I need any help on this!

Bolding the title seems a fine option. But, I am not so sure if it would blend well with all the custom theme. We would have to make sure that the contrast is quite visible(Kind of what Spotify does, with the green colour)

**Pull request closed without merging**
