### PR TITLE
[Theme] Allow customizing Login Page

### PR DESCRIPTION
**Pull request by samarsault**
Extension from https://github.com/navidrome/navidrome/issues/927

Had to make a few changes to the dark theme so that it looks good.
Also, code changes are few, running prettier makes the diff go crazy :)

Screenshot 2021-03-29 at 11 57 53 PM

### CODE REVIEW

**Comment by deluan** [comment]
What about the `<FormSignUp>`? Does the theme looks good on it as well?

**Comment by deluan** [comment]
LGTM, Thanks!

**Comment by deluan** [comment]
I accidentally merged this before some more testing.  I just checked both _Dark_ and current _Spotify-ish_ and they still need some adjustments, both in the FormLogin and FormSignUp (Chrome on macOS):
Screen Shot 2021-03-29 at 11 31 56 PM
Screen Shot 2021-03-29 at 11 31 24 PM
Screen Shot 2021-03-29 at 11 32 31 PM
Screen Shot 2021-03-29 at 11 31 01 PM

**Comment by samarsault** [comment]
Ah, my bad. Fixed in https://github.com/navidrome/navidrome/pull/946

**Pull request merged**
