### PR TITLE
Use local copy of workbox service worker scripts

### LINKED ISSUE #1147: Navidrome connects to google
### Description

I noticed that navidrome is asking my browser to connect to `https://storage.googleapis.com/workbox-cdn/releases/6.1.2/workbox-sw.js`. It is the only remote resource that's fetched.

I blocked `storage.googleapis.com` in ublock and found that navidrome is still working as expected. So my question would be:

* Is workbox needed at all or can it be removed?
* If it's needed, would it be possible to include this js lib in navidrome instead of loading it from google?

I'm using navidrome version 0.42.1.

### PR DESCRIPTION
**Pull request by ajgon**
This is my attempt to fix #1147 . Looks like its not that complicated as `workbox-cli` provides anything necessary to make this process painless. 

However I'm not a JS dev by any means, so I'm not sure if it's a "proper" way of doing this, or just ugly hack (especially the `mv workbox-* workbox` part which ensures consistency of directory name between versions, and keeps only necessary modules). But I believe it's a good starting point, to get rid of this "google call".

### CODE REVIEW

**Comment by deluan** [comment]
Hey, thanks for this. I actually changed some things in your PR:
- Only add prod js, without maps. Reduces the size from 170k to 24k
- Removed it from build. As it is small now, we can add it to source, and have a script to just update it whenever it is required
- Fixed relative paths in `navidrome-service-worker.js`, should now work with BaseUrl != ''

Let me know your thoughts or any concerns

**Comment by ajgon** [comment]
Looking great 👍

**Comment by deluan** [comment]
Hey @certuna, can you please try your "set" of PWA validations with this build?

**Comment by certuna** [comment]
no issues so far

**Pull request merged**
