### PR TITLE
[Spotify-ish] Fix transparent bg in suggestions

### PR DESCRIPTION
**Pull request by samarsault**

### CODE REVIEW

**Comment by samarsault** [comment]
Screenshot 2021-04-02 at 10 51 53 PM

**Comment by deluan** [comment]
LGTM. Thanks!

**Comment by metalheim** [comment]
@samarsault a similar thing happens to the Playlist-List in the "Add Song to Playlist Dialog". (using 0.41.0-SNAPSHOT (d8a1773d)
Would you be so good as to take a look? :)
image

**Comment by samarsault** [comment]
> @samarsault a similar thing happens to the Playlist-List in the "Add Song to Playlist Dialog". (using 0.41.0-SNAPSHOT ([d8a1773](https://github.com/navidrome/navidrome/commit/d8a1773d5087de93efbdedb17cc71b3c5d1a36db))

Yeah, I'm aware of this. Will roll a fix asap. Thanks for pointing it out!

**Comment by samarsault** [comment]
Fixed in https://github.com/navidrome/navidrome/pull/1030

**Pull request merged**
