### PR TITLE
completed night theme

### PR DESCRIPTION
**Pull request by SobhanBera**
Now I think the Night Theme implementation is completed by this PR.

login page night theme screenshot

login page night theme screenshot for signup

### CODE REVIEW

**Comment by deluan** [comment]
This looks great! After some though, I actually feel like "Extra Dark" is a better choice of name, sorry 😛. Can you rename it, please?

PS: Why you keep closing the PRs and opening a new one every time you add a commit?

**Comment by SobhanBera** [comment]
Yeah, I will rename it to "Extra Dark".

And Sorry for closing the PRs. It was having Conflict, so I thought to provide a fresh and clear code.

**Comment by SobhanBera** [comment]
I have changed the theme name from "Night" to "Extra Dark"

**Comment by SobhanBera** [comment]
I have changed the theme name from "Night" to "Extra Dark"

**Comment by SobhanBera** [comment]
I have changed the theme name from "Night" to "Extra Dark"

**Comment by SobhanBera** [comment]
I have changed the theme name from "Night" to "Extra Dark"

And sorry for closing the PRs previously. They contain some code conflicts. So I thought to provide a fresh and clear code.

**Comment by SobhanBera** [comment]
Oops, I got through this for the first time. I didn't know that the files should be formatted using prettier before creating a PR.
For this, I have to do such a large number of commits (for such a simple update).
I will remember this from now. And this will not happen the next time.

**Comment by deluan** [comment]
When you call `make setup-dev`, it should set some Git hooks that make sure the code is properly formatted. Also, it is a good practice to use a prettier plugin in your editor, to auto format on save.

**Comment by deluan** [comment]
LGTM. Thanks!

**Comment by SobhanBera** [comment]
> When you call `make setup-dev`, it should set some Git hooks that make sure the code is properly formatted. Also, it is a good practice to use a prettier plugin in your editor, to auto format on save.

I will remember this next time.

**Pull request merged**
