### PR TITLE
manually add replaygain tags for m4a

### PR DESCRIPTION
**Pull request by kgarner7**
Taglib does not appear to include track/album gain tags in the tags iterator for M4A (aac) containers. This PR seeks to manually add these tags.

### CODE REVIEW

**Comment by deluan** [comment]
Thanks! Is it possible to add a small (no audio) file in the `tests/fixtures` folder with the tags and write a test for this?

**Comment by kgarner7** [comment]
I've added replaygain tests for m4a, mp3, and ogg (it would be nice for one for flac/wav, but need files for that...)

**Comment by deluan** [comment]
> I've added replaygain tests for m4a, mp3, and ogg (it would be nice for one for flac/wav, but need files for that...)

You can create a file with a fraction of a second of audio (like I did with mp3 and ogg) and add tags to it using Picard. Or is there anything else?

By the way, have you just renamed the U2 file to `.m4a`? If that's the case, how can you be sure that `taglib` is actually using your modifications? It is probably still detecting the tags as ID3, not M4A tags.

**Comment by kgarner7** [comment]
The m4a file was generated using ffmpeg on the original to convert to aac, and then I ran aacgain on it to get the tags. Under inspection (exiftool or mutagen), these should be encoded as something with --:com.apple...
I'll see what I can do about flac/wav, but ultimately they shouldn't be blockers for getting the actual fix in (worst case I can make a new PR)

**Pull request merged**
