### PR TITLE
Add missing song information to players and apply EnableCoverAnimation to mobile player.

### LINKED ISSUE #1265: Mobile web interface animates cover art when EnableCoverAnimation is set to false
### Description

When EnableCoverAnimation is set to false the cover art is still animated on the mobile web interface.

### Expected Behaviour

The cover art is not animated.

### Steps to reproduce

1. Set EnableCoverAnimation to false in configuration or via ND_ENABLECOVERANIMATION
2. Confirm that cover art does not animated in desktop web interface.
3. See that cover art does animated in mobile web interface.

### Platform information

 - Navidrome version: 0.44.1
 - Browser and version: Firefox For Android 90.1.3
 - Operating System: Android 9

### Additional information

It's really not a deal breaker. Just an inconsistency.

image

### PR DESCRIPTION
**Pull request by mill1000**
Modifies the mobile and desktop players to add missing basic song info and create a more uniform look. The changes are (obviously) aligned with my preferences and may not fit the project's vision.  I figured I'd at least put them out here as a point of discussion.

## Mobile Player
- Hides the original artist field and adds a new artist field with style matching song title.
- Adds album and song year (if present) to player under artist field, with matching style.

New mobile player fields

- `EnableCoverAnimation` is now applied to the mobile player. When animations are disabled, the cover is displayed square with a width up to 85%. For large mobile screens (e.g. iPad) the maximum width is capped at 600 px. Closes #1265.

Mobile player with cover animations disabled

## Desktop Player
- Song year is added to song info when present in the format of "Artist - Album - Year".

Desktop player with song year

### CODE REVIEW

**Comment by mill1000** [comment]
Thanks!

Just checked with a rectangular cover art, and the behavior could be improved. The lower half stretches to fill the space which causes the buttons to move. That's not ideal. I'll see what I can do about that.

Rectangular cover art


Frankly, the standard behavior isn't that great either, but at least the buttons stay the same.
stock rectangular

**Comment by mill1000** [comment]
Tried fixing the behavior for rectangular album art for both animated and static mobile players. 

Here are the results:

**Static**
Larger Y than X
Screen Shot 2021-08-02 at 20 33 31

Larger X than Y
Screen Shot 2021-08-02 at 20 33 35

**Animated**
Larger Y than X
Screen Shot 2021-08-02 at 20 33 11

Larger X than Y
Screen Shot 2021-08-02 at 20 33 08

**Comment by mill1000** [comment]
And similarly for the desktop player.

**Old behavior**
Y larger than X

X larger than Y

**New behavior**
Y larger than X

X larger than Y

**Comment by deluan** [comment]
Thanks for the PR @mill1000 ! I'll take a look

**Comment by deluan** [comment]
Hey @mill1000, is this ready for review? Is there anything missing?

**Comment by mill1000** [comment]
I have no further changes in mind. I've marked it ready to review.  Hopefully it's not too late the for the next release.

**Pull request merged**
